### ISSUE TITLE
best path for learning ancient history

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#1000]
Take a look [here](https://my.mindnode.com/fSJLUqJyrAMRnmZUyRmkG1Z2Dqur8ksgCfREbaqd).

If you think there is a better way one can learn ancient history or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on ancient history that are missing or you wish something was added, you can say it here.

**Comment by Blake575** [comment]
[This](https://youtu.be/9FrHGAd_yto?list=PL023BCE5134243987) is a fantastic Yale course that is an introduction to Ancient Greek History.

**Comment by nikitavoloboev** [comment]
Added it. Thank you @Blake575
