### ISSUE TITLE
best path for learning Norwegian language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#1032]
Take a look [here](https://my.mindnode.com/5p1Bs3PmWrGwzAeW3zwJPkxshctFQqjtrR3ELyNx).

If you think there is a better way one can learn Norwegian language or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on Norwegian language that are missing or you wish something was added, you can say it here.

**Comment by averageunicorn** [comment]
This is an online newspaper in Easy Norwegian, good for first reading practice: http://www.klartale.no/

**Comment by nikitavoloboev** [comment]
Added it. Thank you @averageunicorn
