### ISSUE TITLE
best path for learning tmux

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#1033]
Take a look [here](https://my.mindnode.com/mk1hLazUx97D8tymkePWZPuwhY2LCFDXTN4vF5RV).

If you think there is a better way one can learn tmux or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on tmux that are missing or you wish something was added, you can say it here.

**Comment by flexbox** [comment]
Learn how to quit vim 😂 

BTW This game is a great introduction. As a teacher, I noticed that some students try to dig on vim shortcuts more easily https://vim-adventures.com/

**Comment by nglgzz** [comment]
Oh yeah I've tried that game, it's pretty awesome :smile:
