### ISSUE TITLE
best path for learning Excel

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#1035]
Take a look [here](https://my.mindnode.com/psD7CyDsn1PnCNq8xpxK9983oC4nDSYGbN7xUJJ8).

If you think there is a better way one can learn Excel or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on Excel that are missing or you wish something was added, you can say it here.

**Comment by Awram** [comment]
I have found [](http://chandoo.org/ ) to be an amazing resource for learning about Excel.

**Comment by nikitavoloboev** [comment]
Awesome. I have added it. :)

**Comment by Awram** [comment]
@nikitavoloboev Lightning fast!
