### ISSUE TITLE
best path for learning classical music

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#1043]
Take a look [here](https://my.mindnode.com/sf6D2ZsdvDhHbBquoKmfP6fdAiwD4RsE1Dqws4Fg).

If you think there is a better way one can learn classical music or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on classical music that are missing or you wish something was added, you can say it here.

**Comment by mrlund** [comment]
Suggested addition: https://www.google.it/_/chrome/newtab?espv=2&ie=UTF-8
