### ISSUE TITLE
best path for learning juggling

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#1047]
Take a look [here](https://my.mindnode.com/YqGswrpLQPz7JQ2jLsqsXRQbVMBJeeMdiB6BFtRX).

If you think there is a better way one can learn juggling or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on juggling that are missing or you wish something was added, you can say it here.

**Comment by OfficialCJunior** [comment]
http://www.wikihow.com/Juggle - clearly is an amazing resource for learning it.
http://jugglefit.com/how-to-juggle.html -offers videos and tips.

Thank you! :)
