### ISSUE TITLE
best path for learning adobe illustrator

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#1050]
Take a look [here](https://my.mindnode.com/s8pqMXQviFER3HQHDpWWeGsv7fTN3BBerWQezgJH).

If you think there is a better way one can learn adobe illustrator or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on adobe illustrator that are missing or you wish something was added, you can say it here.

**Comment by OfficialCJunior** [comment]
https://www.lynda.com/Illustrator-training-tutorials/227-0.html -offers courses to learn it.
