### ISSUE TITLE
best path for learning spark web framework

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#1055]
Take a look [here](https://my.mindnode.com/wwLQURAiEZE7WtMVy22LzVcsy3oVQUxEyzPA6Fd1).

If you think there is a better way one can learn spark web framework or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on spark web framework that are missing or you wish something was added, you can say it here.

**Comment by cricket007** [comment]
Unfortunately, Awesome Spark links to **Apache Spark**, a big data framework, not SparkJava, the web framework.

**Comment by nikitavoloboev** [comment]
Thank you @cricket007, I changed it.
