### ISSUE TITLE
best path for learning spring java framework 

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#1056]
Take a look [here](https://my.mindnode.com/pPHve7k8EUpnEYDcqFCwivq4CNeqGDDB4fDEFkbW).

If you think there is a better way one can learn spring java framework or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on spring java framework that are missing or you wish something was added, you can say it here.

**Comment by jonk1993** [comment]
I recently found https://itunes.apple.com/us/podcast/spring-boot-with-josh-long/id1019576853?i=1000384792674&mt=2

It's a fairly helpful interview with a Spring developer Josh Long. He initially goes over the reasoning behind starting the Spring Framework, it's growth, and eventually how Spring Boot fits in.

I thought this might work as an item attached to the "help" node for either Spring Framework or Spring Boot? It doesn't necessarily give a tutorial on the framework, but I thought it provides some good context and expected use cases.
