### ISSUE TITLE
best path for learning content management systems

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#1057]
Take a look [here](https://my.mindnode.com/DjBoPdaHkiMDtudWrt7YY8p6Xs4pqGmp3q85ocSR).

If you think there is a better way one can learn content management systems or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on content management systems that are missing or you wish something was added, you can say it here.

**Comment by jlrg1992** [comment]
Joomla should be added, it's an important one.

**Comment by nikitavoloboev** [comment]
Added it. Thank you @jlrg1992 💙

**Comment by mrlund** [comment]
Suggested addition: https://www.google.it/_/chrome/newtab?espv=2&ie=UTF-8

**Comment by flexbox** [comment]
Hello @nikitavoloboev 
I think you can add a top level node like

- Build-in solutions
  - Wordpress
  - Drupal
  - …
- API first cms (_Prerequire: link to api 101_)
  - https://css-tricks.com/api-based-cms-approach/
  - solutions:
    - https://www.contentful.com/guides/
    - https://prismic.io/quickstart

Because nowadays the web world is API first, what do you think?

**Comment by nikitavoloboev** [comment]
Hey @flexbox 

I added your suggestions [here](https://learn-anything.xyz/web-development/content-management-systems). 

Is this what you were thinking of?
