### ISSUE TITLE
Integrate Draw.io as an authoring tool for the mindMap

### ISSUE THREAD

**Issue by wgong** [learn-anything/maps#1179]
Draw.io is an awesome drawing tool available free online. Since mindnode is only available for Mac user, it would be good to extend map contributor base to non-Mac users.
I am working on a utility prototype to convert Draw.io exported xml doc to json file which will be compatible to Learn Anything mind-map json format.
You are welcome to suggest improvement on this thread

parsed json (work in progress)
https://goo.gl/photos/cicaALKFHPsN7MFt5

map design in Draw.io:
https://goo.gl/photos/UehfjAKBzRzmNstV9

final target should look like this
https://goo.gl/photos/mUQwiJDhx2P74Sav6

**Comment by nikitavoloboev** [comment]
Have you made any progress on this @wgong 

It's an awesome idea we would love to add to new version of Learn Anything we are building. Adding a way to visually create guides & maps as part of a study guide.

We can discuss it in more detail with you if you wish. But your approach is very interesting.
