### ISSUE TITLE
Missing/broken links

### ISSUE THREAD

**Issue by rodricios** [learn-anything/maps#1208]
Hi. Very cool tool. 

Just wanted to bring up a few dead links (most of which seem to have been temporarily hosted by fkcd.ca

On the [general artificial intelligence](https://learn-anything.xyz/artificial-intelligence/general-artificial-intelligence) map, the link to ["agi concept map"](https://fkcd.ca/uuk.svg) ls broken. 

On the [computer science](https://learn-anything.xyz/computer-science) map, the [cs concept map](https://fkcd.ca/b7d.svg) link is broken.

For [neuroscience](https://learn-anything.xyz/neuroscience), [neuroscience concept mind map](https://learn-anything.xyz/neuroscience) link is broken.

Lastly, on the [Machine learning](https://learn-anything.xyz/machine-learning) map, the [machine learning concept map](https://fkcd.ca/EpU.svg) link is broken as well.

Thanks

**Comment by nikitavoloboev** [comment]
Thank you @rodricios 

I have removed the dead links. The update with changes should be up soon. 🙂
