### ISSUE TITLE
best path for learning front end development

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#431]
Take a look [here](https://my.mindnode.com/zRGj6Bjd1T31sVhsJz4HcNbCCz7ZMgKNqJSWSjyt#392.4,-184.2,2). 

If you think there is a better way one can learn front end development or you think the way the nodes are structured in a wrong way, please say it here.

Also if you think there are some really amazing resources on front end development that are missing or you wish something was added, you can say it here.

**Comment by keenanamigos** [comment]
Within JavaScript -> Basics, I think FreeCodeCamp should be added. It's an excellent project-based resource that takes learners from novice to advanced with material that is constantly being updated and improved. Really awesome project you have going on and I love what you've done so far! 

FreeCodeCamp Website: https://www.freecodecamp.com/
FreeCodeCamp Repo: https://github.com/freeCodeCamp/freeCodeCamp

**Comment by nikitavoloboev** [comment]
Oh definitely. I actually have free code camp added as intro to [web development](https://my.mindnode.com/85uh2iN4GPhBJpuyyuWks5a6niyypQA5TPBCGnAN#521.7,-260.4,2) but I have added it to [javascript](https://my.mindnode.com/QQzCynmUtZpAuyGipqxsvRJ6NPn477o9cSjCGqqR#-98.1,-52.5,2) too. Thank you a lot. 

If you have anything more to share, please do. :)
