### ISSUE TITLE
best path for learning art

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#434]
Take a look [here](https://my.mindnode.com/LqjxehvfzXszoTjqzLTdcrfwD6c4mSFck9PDgxD8#70.1,-225.5,2).

If you think there is a better way one can learn art or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on art that are missing or you wish something was added, you can say it here.

**Comment by Blake575** [comment]
You Can Draw in 30 Days by Mark Kistler.
http://www.goodreads.com/book/show/3113980-you-can-draw-in-30-days

This would be great in the drawing basics section. Drawing on the Right Side of the Brain didn't work for me but this one did.

**Comment by nikitavoloboev** [comment]
Added it. Thank you @Blake575

**Comment by Blake575** [comment]
This [video](https://youtu.be/dnflBERf2zM) is an in-depth look at what a visual library is and how to develop it. It helps clarify how artists are seemingly able to just make stuff up. I found it to be helpful.

**Comment by Blake575** [comment]
1, I think there should be a creative writing section. [This](https://youtu.be/N4ZDBOc2tX8?list=PLH3mK1NZn9QqOSj3ObrP3xL8tEJQ12-vL) free lecture series taught by popular fantasy author Brandon Sanderson is great.
2. [Here](https://medium.com/@immeasurablematt/dr-jordan-b-petersons-10-step-guide-to-clearer-thinking-through-essay-writing-1ab79a94937) is how to write an essay by Dr. Jordan B. Peterson. It's useful for those that want to improve their writing and thinking.

**Comment by nikitavoloboev** [comment]
Added it. Thank you @Blake575
