### ISSUE TITLE
best path for learning artificial intelligence

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#435]
Take a look [here](https://my.mindnode.com/wzysPxEVDVNYXebyN8Sp9qAg4mQ56btHbicx99ac#-6.5,-250.4,2).

If you think there is a better way one can learn artificial intelligence or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on artificial intelligence that are missing or you wish something was added, you can say it here.

**Comment by humford** [comment]
Two things:
1. it seems like the nodes linking to other maps are overlapping here: https://learn-anything.xyz/artificial-intelligence

**Comment by humford** [comment]
2. MIT runs an excellent AI programming competition called Battlecode (https://www.battlecode.org/) which I think would be an excellent addition, perhaps under a new subnode of "competitions" or under "interesting". I could also suggest more competitions if you do go forward in creating a new subnode.

**Comment by nikitavoloboev** [comment]
I [added competitions](https://my.mindnode.com/wzysPxEVDVNYXebyN8Sp9qAg4mQ56btHbicx99ac) node. Feel free to add more, they do sound quite interesting. :)

**Comment by nikitavoloboev** [comment]
Also we are still thinking how we can fix overlapping.

**Comment by nikitavoloboev** [comment]
Also for battecode, only students can take part in it?

**Comment by humford** [comment]
@nikitavoloboev its open to anyone, but the sponsored prizes are only for students, I competed this year so that's how I know about it.

A few more competitions:
https://halite.io/
http://vindinium.org/
