### ISSUE TITLE
best path for learning computer hardware

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#439]
Take a look [here](https://my.mindnode.com/Lf272jyyVyWWmRPpxs8z4GvsxQqGPLfpZrVhYnMn#-292.5,-354.9,2).

If you think there is a better way one can learn about computer hardware or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on computer hardware that are missing or you wish something was added, you can say it here.

**Comment by aw1231** [comment]
The Nand2Tetris project is a great intro to building computers from scratch (albeit virtually): http://www.nand2tetris.org/

**Comment by nikitavoloboev** [comment]
Thank you @aw1231, I added it. 💙
