### ISSUE TITLE
best path for learning computer vision

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#441]
Take a look [here](https://my.mindnode.com/mCmNsBxeiGdRqYefxaq2HXYMKxf8sFWq92qYtMyU#119.8,-247.5,2).

If you think there is a better way one can learn computer vision or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on computer vision that are missing or you wish something was added, you can say it here.

**Comment by samuelshih** [comment]
Textbook for computer vision by Richard Szeliski
http://szeliski.org/Book/drafts/SzeliskiBook_20100903_draft.pdf

**Comment by nikitavoloboev** [comment]
Hey @samuelshih . Thank you a lot. I have added it. Will be u shortly. 💙
