### ISSUE TITLE
best path for learning cryptocurrencies

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#442]
Take a look [here](https://my.mindnode.com/7TUvLNzE4aUwzNqXurPdcyenQR5sYx9XsJjYcQcZ).

If you think there is a better way one can learn about cryptocurrencies or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on cryptocurrencies that are missing or you wish something was added, you can say it here.

**Comment by brandonskerritt51** [comment]
I think the blockchain should be added as an extra branch to the mindmap.
