### ISSUE TITLE
best path for learning economics

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#447]
Take a look [here](https://my.mindnode.com/FHh7spgcDGWdg72U6L4u34VRCrW9kLswUHQoXBMs#8.2,-506.1,2).

If you think there is a better way one can learn economics or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on economics that are missing or you wish something was added, you can say it here.

**Comment by devinmcnulty** [comment]
There is definitely a lack of detail and structure to the economics node. The basics should really branch off into microeconomics, macroeconomics, etc. Business, investing, and financial independence are rather specific areas and certainly not the focus of _economic_ study. Khanacademy certainly has great videos on microeconomics, macroeconomics and international economics. I'm an economics student and I would be glad to link resources for these respective nodes (and possible sub nodes) to really flesh out the economics study guide

**Comment by nikitavoloboev** [comment]
Thank you. Can you take a look at [this](https://my.mindnode.com/FHh7spgcDGWdg72U6L4u34VRCrW9kLswUHQoXBMs) @devinmcnulty? I have added micro and macro economics. Although I don't really know how to structure the nodes. I do want to include investing and financial independence but not really sure how to structure it.

**Comment by devinmcnulty** [comment]
Perhaps you could put Investing and Personal Finance both under a 'Finance' node. Otherwise I think it looks good. I'll dig through what I have and post some resources that have been useful to me later. Love this idea!

**Comment by nikitavoloboev** [comment]
I have changed it. Thank you a lot for your help. 💙

**Comment by jessicayung** [comment]
[Ben Lambert's Youtube video series](https://www.youtube.com/user/SpartacanUsuals) is the best online resource I've come across for learning econometrics so far: https://www.youtube.com/user/SpartacanUsuals

**Comment by nikitavoloboev** [comment]
Thank you @jessicayung 

I added it 💙
