### ISSUE TITLE
best path for learning game development

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#449]
Take a look [here](https://my.mindnode.com/rMqH25BBnT8N9Frhv3L6YCk8NozigyGWgjrgPmjE#77.8,-47.1,2).

If you think there is a better way one can learn game development or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on game development that are missing or you wish something was added, you can say it here.

**Comment by Katamori** [comment]
Would you add a "game frameworks" map? And for each framework, a separate map would be worthy as well, as all of them mean a different topic.

To list a few:

* Allegro for C++

* XNA for C#

* LÖVE a.k.a. Love2D for Lua

* PhaserJS for Javascript (as well as HTML5 actually)

* libGDX for Java

Also for game engines:

* Unity

* and you can list practically any video game engine ever developed (id Tech series, Unreal Engine, Crytek, Source, Build

Also platforms:

* Stencyl

* GDevelop

* Game Maker Studio
