### ISSUE TITLE
best path for learning health

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#450]
Take a look [here](https://my.mindnode.com/4LknBLWzBESbxERfpYQZsa2Fv1k3Lne1FjVsD4ys#-11.7,-27.4,2).

If you think there is a better way one can learn about health or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on health that are missing or you wish something was added, you can say it here.

**Comment by Mister-GoodwinLu** [comment]
though not directly related to improving health, myfridgefood.com helps know about what recipes you have based on current food
