### ISSUE TITLE
best path for learning linux

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#456]
Take a look [here](https://my.mindnode.com/7N2X8wXv19NAjB3gdrFkfzqqT6LpDyzLAJVfx15e).

If you think there is a better way one can learn linux or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on linux that are missing or you wish something was added, you can say it here.

**Comment by Jedeu** [comment]
I would add [Linux Academy](https://linuxacademy.com/) as another resource to learn Linux. Really awesome content and the labs are the reason people pay for it. I've also heard people being able to pass certifications using this website alone.

**Comment by shotgunner** [comment]
@nikitavoloboev "here" in your text : "Take a look here" is not link.

**Comment by nikitavoloboev** [comment]
@shotgunner I fixed the link

Thank you @Jedeu, I've added it. :)
