### ISSUE TITLE
best path for learning machine learning

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#457]
Take a look [here](https://my.mindnode.com/k954FWFNztnkphWmNqqHz2dqQW41LeP1SLqkqqjs#456.9,-856.0,1).

If you think there is a better way one can learn machine learning or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on machine learning that are missing or you wish something was added, you can say it here.

**Comment by agrawal-priyank** [comment]
I would like to recommend this [ML specialization](https://www.coursera.org/specializations/machine-learning) by University of Washington on Coursera. 

It is way better than other online courses as it dives deep into the machine learning algorithms ranging from regression, classification to clustering and retrieval and they have assignments to implement them from scratch and apply on various datasets.

Thanks!

**Comment by nikitavoloboev** [comment]
Thank you a lot @agrawal-priyank. I [have aded it](https://my.mindnode.com/k954FWFNztnkphWmNqqHz2dqQW41LeP1SLqkqqjs). Looks really interesting too.

**Comment by agrawal-priyank** [comment]
Certainly is 👍 .
