### ISSUE TITLE
best path for learning marketing

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#459]
Take a look [here](https://my.mindnode.com/Wm2fSqKWEJyyZ3LYZsgy2x6Yb8te49t968qqypUs#79.7,-75.0,5).

If you think there is a better way one can learn marketing or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on marketing that are missing or you wish something was added, you can say it here.

**Comment by mijustin** [comment]
A few good resources here:

**Book:** [Traction](http://tractionbook.com/)
**Course**: [Marketing for Developers](https://devmarketing.xyz)

**Comment by nikitavoloboev** [comment]
Thank you a lot. I do prefer free content and courses over paid but I [have added them](https://my.mindnode.com/Wm2fSqKWEJyyZ3LYZsgy2x6Yb8te49t968qqypUs).

**Comment by mijustin** [comment]
I just reduced the price to $149. I had tons of devs buy at $299. I messaged them individually to say I was testing a new price (and to give them $150 store credit). Almost all of them replied that they felt the course was worth more than $300. 

We'll see what folks think of the new price!
