### ISSUE TITLE
best path for learning natural language processing

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#461]
Take a look [here](https://my.mindnode.com/nFFywmhppMRxw1Z6n7QNxikisQo9q9egH5jL8PfD#171.2,5.5,2).

If you think there is a better way one can learn natural language processing or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on natural language processing that are missing or you wish something was added, you can say it here.

**Comment by rhuanbarros** [comment]
You can put this link for the class that come before "Natural Language Processing with deep learning" on Stanford's Classes.
https://www.youtube.com/playlist?list=PL6397E4B26D00A269

**Comment by nikitavoloboev** [comment]
Added it. Thank you @rhuanbarros

**Comment by Hieunv1996** [comment]
@rhuanbarros your video have been deleted. @nikitavoloboev please update or remove that.
