### ISSUE TITLE
best path for learning philosophy

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#464]
Take a look [here](https://my.mindnode.com/DaLRfu3ipMHEkhxuzqKTgbZPLmVGTmN7khBS3xqZ#-28.4,-144.3,2).

If you think there is a better way one can learn philosophy or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on philosophy that are missing or you wish something was added, you can say it here.

**Comment by Blake575** [comment]
Wes Cecil's audio recordings are a fun and engaging introduction to philosophical ideas and thinkers. Link to his channel is [here](https://www.youtube.com/channel/UC9ff15w4ufviWfv9UfIuByA)

My favorite is his lecture on [Nietzsche.](https://youtu.be/r1J7OoErWvs)

**Comment by nikitavoloboev** [comment]
That is a really interesting idea. If you add few more questions that can go there and good resolutions to the questions, I will add it. :)
