### ISSUE TITLE
best path for learning physics

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#465]
Take a look [here](https://my.mindnode.com/RfCpjqozA6Aq3j38RvzUnZrhFGMnpCsbRrpAsUWj#56.0,116.9,2).

If you think there is a better way one can learn physics or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on physics that are missing or you wish something was added, you can say it here.

**Comment by akkatracker** [comment]
Walter Lewin's MIT lectures are a very popular introduction to Physics (I'd say slightly better than Stanford's Classical Mechanics videos)

**Comment by nikitavoloboev** [comment]
I have added it, thank you.

**Comment by mattj256** [comment]
I didn't see a GitHub issue for special relativity so I'm posting here.

World Science University (worldscienceu.com) has some good online courses.

"Space, Time and Einstein: A Conceptual Tour of Special Relativity with Brian Greene"
Hardly any math, designed for laypeople who want to understand the core concepts of special relativity.
http://www.worldscienceu.com/courses/university/space-time-and-einstein

"Special Relativity: A Math-Based Introduction with Brian Greene"
A free online class on special relativity. "Assumes high school physics and mathematics. Familiarity with calculus is useful but not essential."
http://www.worldscienceu.com/courses/university/special-relativity

**Comment by nikitavoloboev** [comment]
Thank you a lot @mattj256. I have added both of the courses to [special relativity](https://my.mindnode.com/gLpu3axPp2y3uXJoq4G5F2bCzbLNDn9Vi1rnaZLH). It is in [physics](https://my.mindnode.com/RfCpjqozA6Aq3j38RvzUnZrhFGMnpCsbRrpAsUWj#-88.0,-67.1,2).

They look really awesome. If you have anything you wish was added, please say. 💚

**Comment by mattdax** [comment]
Missing out on quite a bit of hishschool physics :( 


http://www.flippingphysics.com/algebra.html
http://www.learnapphysics.com/apphysics1and2/index.html

**Comment by nikSmdgr** [comment]
I found Susan Fowler's guide to learn physics extremely valuable. It is really well structured and contains great learning materials.

https://www.susanjfowler.com/blog/2016/8/13/so-you-want-to-learn-physics

**Comment by nikitavoloboev** [comment]
Oh wow, that's amazing. Thank you @nikSmdgr

**Comment by HenkeDaniil** [comment]
https://www.khanacademy.org/science/physics

**Comment by nikitavoloboev** [comment]
Hey @HenkeDaniil 

It's already added if you look. :)

**Comment by humford** [comment]
Not sure where this might fit in, either in "basics" or with each course under its respective subdiscipline, but Leonard Susskind has an excellent series of introductory physics courses with a focus on broad concepts over rigor and the underlying math. It's very good for lay people looking for essential knowledge.

http://theoreticalminimum.com/courses

**Comment by nikitavoloboev** [comment]
Thank you @humford, will add it now :)
