### ISSUE TITLE
best path for learning programming

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#466]
Take a look [here](https://my.mindnode.com/XK73eU8WNHy5qHEnsKTKqSdsVkXzs2iMtvTmgYpc#354.6,-28.1,-1).

If you think there is a better way one can learn programming or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on programming that are missing or you wish something was added, you can say it here.

**Comment by Goodegamage** [comment]
Am new to programming but whenever I search for elements on Google, w3schools comes out, just curious where does it play in all of this.

**Comment by nikitavoloboev** [comment]
Hey @Goodegamage. The idea of this search engine and mind maps is to provide the most efficient paths for learning any of the topics. Sometimes w3schools is really great but often there are better resources out there.

**Comment by Goodegamage** [comment]
I agree with you, I find freecodecamp more resourceful

**Comment by danweiner** [comment]
What about Scratch/code.org/woof.js? Other block based programming resources?

**Comment by nikitavoloboev** [comment]
There is no limit to what resource can be added. It just has to be good and ideally free. So yeah Scratch and code.org are great resources. I will add them. :)

**Comment by danweiner** [comment]
I actually just wrote a blog post on learning to code. I love the topic. If you would like you can read or skim the post and take whatever resources you would like. https://medium.com/@daweiner16/code-like-billy-madison-3aafc9d84606?source=linkShare-468cee8a9d13-1497307367
