### ISSUE TITLE
best path for learning psychology

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#467]
Take a look [here](https://my.mindnode.com/cmk4fh551FmyBm5Eg3vAbj9zruxk3W41XNreG4vy).

If you think there is a better way one can learn psychology or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on psychology that are missing or you wish something was added, you can say it here.

**Comment by Blake575** [comment]
I think a persuasion section should be here.

Some starting material includes:
1. A [reading list](http://blog.dilbert.com/post/129784168866/the-persuasion-reading-list) curated by Scott Adams:

2. A [video](https://youtu.be/_DGdDQrXv5U?list=LLHJbZ1tEtBZFpc0NdU_HtzQ) by Will Schoder that analyzes Mr. Rogers testifying to the U.S. senate and how he used persuasive techniques to secure funding for PBS.

**Comment by nikitavoloboev** [comment]
Sounds really interesting. Thank you @Blake575 

Will add it.

**Comment by Blake575** [comment]
An Evolutionary Psychology map would be great as well. 

Robert Sapolsky teaches my favorite course on the subject. Link is [here](https://youtu.be/NNnIGh9g6fA?list=PLMwddpZ_3nkAWijQlBnkwnr9wfcuderVe).

**Comment by nikitavoloboev** [comment]
Added it. Thank you @Blake575
