### ISSUE TITLE
best path for learning virtual reality

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#471]
Take a look [here](https://my.mindnode.com/mKhEXHiMUXpGgfJxDkqbgyxN3MRp3bwug96a9zo2).

If you think there is a better way one can learn virtual reality or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on virtual reality that are missing or you wish something was added, you can say it here.

**Comment by Utopiah** [comment]
Consider instead https://aframe.io/aframe-school/

**Comment by nikitavoloboev** [comment]
I [have added it](https://my.mindnode.com/CWsQJ418QKxqEztQEYyozPWHiqxEK9JnZBgdSbpz). Thank you.
