### ISSUE TITLE
best path for learning web development

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#472]
Take a look [here](https://my.mindnode.com/85uh2iN4GPhBJpuyyuWks5a6niyypQA5TPBCGnAN#521.7,-260.4,2).

If you think there is a better way one can learn web development or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on web development that are missing or you wish something was added, you can say it here.

**Comment by Ziinc** [comment]
Would suggest adding a fullstack framework branching out from the "basics" node.
I can contribute resources pertaining to the Meteor javascript fullstack framework
other fullstack frameworks would be MEAN (Mongo + Express + AngularJS + Node.js) and MERN (Mongo + Express + React js + Node.js)

**Comment by nikitavoloboev** [comment]
Thank you @Ziinc. I have added full stack from basics [like this](https://my.mindnode.com/85uh2iN4GPhBJpuyyuWks5a6niyypQA5TPBCGnAN). Here is the [full stack mind map](https://my.mindnode.com/YfXtXRQ4Vys8SZaxwKETATNSWX4rbhHeq6xPxLjm). 

Please share resources on learning them. I will add them. If you think, it can be structured better, please say. 💙

**Comment by shotgunner** [comment]
[Web Developer Road-map 2017](http://github.com/kamranahmedse/developer-roadmap)
