### ISSUE TITLE
best path for learning keras library

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#476]
Take a look [here](https://my.mindnode.com/rApczcRbzmMrgkZtP6QmEyTRGUvgiyThASZrPP5C#-26.1,47.7,2).

If you think there is a better way one can learn keras library or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on keras that are missing or you wish something was added, you can say it here.

**Comment by yvan** [comment]
i think it may be a good idea to put the [fastai course](http://course.fast.ai/lessons/lesson1.html) on here it is done in keras. it is very good and will quickstart you. they built these helper classes that make it very easy to retrain the last layer of VGG, they also help you get setup with a p2 gpu instance on aws. speaking from personal experience not having those tools/working baseline it would take 10x longer to figure out how this stuff works.

**Comment by nikitavoloboev** [comment]
I [have added](https://my.mindnode.com/rApczcRbzmMrgkZtP6QmEyTRGUvgiyThASZrPP5C) it. Thank you. I might actually try to do it soon too as I always wanted to get some hands on practice with machine learning outside of reading all the theory.

**Comment by yvan** [comment]
[andrew ng's coursera course](https://www.coursera.org/learn/machine-learning) is really good for theory (i did the course). coursera + fastai can get you going with a good foundation pretty quickly. what i'm doing right now.

**Comment by nikitavoloboev** [comment]
Yeah I have added Andrew's course to [machine learning](https://my.mindnode.com/k954FWFNztnkphWmNqqHz2dqQW41LeP1SLqkqqjs#356.7,-852.8,1). Thanks.

**Comment by goxul** [comment]
[This can be useful for an introduction to Keras](https://www.youtube.com/playlist?list=PLFxrZqbLojdKuK7Lm6uamegEFGW2wki6P)
