### ISSUE TITLE
best path for learning c programming language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#483]
Take a look [here](https://my.mindnode.com/Cy6YFfoRFvBbgMMWgyN2zaqhj9KPjB23fwxvN2GB).

If you think there is a better way one can learn c programming language or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on c programming language that are missing or you wish something was added, you can say it here.

**Comment by akkatracker** [comment]
You have the wrong link attached here but most people would agree that Harvard's CS50 is an excellent C primer. Otherwise Richard Buckland's Computing 1 Videos on Youtube (his recordings of his lectures at UNSW) are slower but also excellent.

**Comment by nikitavoloboev** [comment]
Thank you a lot. I have changed the link. I [added the course](https://my.mindnode.com/Cy6YFfoRFvBbgMMWgyN2zaqhj9KPjB23fwxvN2GB). The CS50 course is [done in python](https://cs50.harvard.edu/weeks) though it seems, no? 

I can add it to computer science basics though.

**Comment by akkatracker** [comment]
The first 6 lectures are in C - the last few are Python. Actually not a bad
idea to put in Computer Science Basics instead or as well (Maybe put
Richard Buckland's lectures here).

Also more of these more recent links are wrong - the older issues are fine,
just a few on the first page.
