### ISSUE TITLE
best path for learning entrepreneurship

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#496]
Take a look [here](https://my.mindnode.com/7wRp4x4AGyQt7oxU2PzZpSEGudSns76n1f9WXD6Y).

If you think there is a better way one can learn entrepreneurship or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on entrepreneurship that are missing or you wish something was added, you can say it here.

**Comment by tedcarstensen** [comment]
I'd humbly submit the Heavybit Library as a high quality resource for entrepreneurship advice in the form of lecture videos, podcasts, and blog posts.

https://www.heavybit.com/library/

Or perhaps more specifically, this tag https://www.heavybit.com/library/topic/general-management/
