### ISSUE TITLE
best path for learning environmental science

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#497]
Take a look [here](https://my.mindnode.com/2qWdikpzGwN6GkfyyevpW85tXxACgjqWGfxyJ7Ph).

If you think there is a better way one can learn environmental science or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on environmental science that are missing or you wish something was added, you can say it here.

**Comment by HazeHub** [comment]
Not sure it's the best place to add it but the mindmap lacks geology.

**Comment by nikitavoloboev** [comment]
Thank you @HazeHub. I created a mind map for it under new [Earth science](https://my.mindnode.com/9rmJaLMzJ4Wq59fVfrzF5jA7u3ZFVbUvP1fYNyq3) node.

[Here](https://github.com/nikitavoloboev/learn-anything/issues/761) is GitHub issue of it, if you want to improve it. :)
