### ISSUE TITLE
best path for learning distributed computing

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#498]
Take a look [here](https://my.mindnode.com/2ZYrG1D2SizuM5YzrnCNQdNqzZXC1N5nH2aTMbVd#-131.5,-133.6,2).

If you think there is a better way one can learn distributed computing science or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on distributed computing that are missing or you wish something was added, you can say it here.

**Comment by ryankrage77** [comment]
Perhaps include something on Folding@Home? It's the largest public distributed computing project in the world. folding.stanford.edu

**Comment by nikitavoloboev** [comment]
Added it. Thank you @ryankrage77
