### ISSUE TITLE
best path for learning python programming language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#500]
Take a look [here](https://my.mindnode.com/cmzq9sEGAyyNyeZrNA7UyQa8JpsqHf9QzStwFqGT).

If you think there is a better way one can learn python programming language or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on python programming language that are missing or you wish something was added, you can say it here.

**Comment by isaacelee** [comment]
https://learnpythonthehardway.org/book/
Website I've been using to learn python. Would definitely recommend.

**Comment by nikitavoloboev** [comment]
Hey @isaacelee, it is a pretty good resources but sadly he is teaching python 2. I think it is best to learn python 3 straight away and there are multiple great resources available already for that. :)

**Comment by shotgunner** [comment]
[learn x in y minutes :)](https://learnxinyminutes.com/docs/python3/)

**Comment by nikitavoloboev** [comment]
I have added it. Thank you @shotgunner

**Comment by shotgunner** [comment]
[overapi.com](http://overapi.com/python)

**Comment by nikitavoloboev** [comment]
Add it too, thank you. :)

**Comment by shotgunner** [comment]
thanks :+1: @nikitavoloboev

**Comment by lulucca12** [comment]
There is a great site that I like to use to learn different programming languages; it has python! [http://www.sololearn.com/](url)

**Comment by shotgunner** [comment]
interactive game site for learn python and compete with others : 
[checkio.org](py.checkio.org)

**Comment by danweiner** [comment]
How about linking to Django for web dev content? Love the site but would like to see more how concepts link together. Python leads to Django. JS leads to react. That kind of thing

**Comment by nikitavoloboev** [comment]
I agree with you @danweiner. We already link maps together in some mind maps and we plan to do it more often. The goal of this is both to provide the most efficient paths for learning anything and also to show how everything is interconnected.

**Comment by lapisdecor** [comment]
The Hitchhiker’s Guide to Python!
http://docs.python-guide.org/en/latest/

**Comment by prith13** [comment]
Codecademy is great for absolute beginners to learn the syntax and fundamentals and it is my go-to resource to learn new languages: [](https://www.codecademy.com/learn/python)

Another good one: [](https://learnpythonthehardway.org/book/)

For biologists: [](http://pythonforbiologists.com/)

**Comment by shashank-sharma** [comment]
For data structures and algorithms this site is the best and it has python 3 version in it so its worth adding.
http://interactivepython.org/runestone/static/pythonds/index.html

**Comment by nikitavoloboev** [comment]
Added it. Thank you @shashank-sharma :)

**Comment by namangt68** [comment]
Udacity basic course on python is also good for those who prefer video based learning.

https://www.udacity.com/course/programming-foundations-with-python--ud036

**Comment by shotgunner** [comment]
[pythontutor.com](pythontutor.com)
Visualize python Code (also java, javascript, C, and other)1
