### ISSUE TITLE
best path for learning git

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#501]
Take a look [here](https://my.mindnode.com/dzhbs3FRB4z143969SjnPEDspe1Gp3SEppissAqy).

If you think there is a better way one can learn git or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on git that are missing or you wish something was added, you can say it here.

**Comment by shotgunner** [comment]
free online book for learn git => [git tower book](git-tower.com/learn/)
Git How To is a guided tour that walks through the fundamentals of Git => [githowto](https://githowto.com/)
learn git with sample ruby project => [git immestion](http://gitimmersion.com/)

**Comment by nikitavoloboev** [comment]
Added it. Thank you @shotgunner I've added them
