### ISSUE TITLE
best path for learning javascript libraries 

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#502]
Take a look [here](https://my.mindnode.com/5PazdXmKxEq1mDpksAfWUZFdJTpvAHpti6Cir1S2).

If you think there is a better way one can learn javascript libraries or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on javascript libraries that are missing or you wish something was added, you can say it here.

**Comment by thiloo** [comment]
template engines should be added

Handlebars (http://handlebarsjs.com/)
Pug (https://pugjs.org/api/getting-started.html)

**Comment by nikitavoloboev** [comment]
I have added them @thiloo. Thank you. 💙

**Comment by tcrack326** [comment]
Angular and AngularJS should be in the front-end "choose a framework".

**Comment by nikitavoloboev** [comment]
Will add them now. Thank you @tcrack326
