### ISSUE TITLE
best path for learning node.js

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#503]
Take a look [here](https://my.mindnode.com/66sFsUMNvxTztuXk4hHSKRByUXqnASaLTXMNrNkv).

If you think there is a better way one can learn node.js or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on node.js that are missing or you wish something was added, you can say it here.

**Comment by nhsz** [comment]
[The Node Way](http://thenodeway.io/) is an excellent collection of articles that should be included.

**Comment by Katamori** [comment]
As well as [RisingStack articles.](https://risingstack.com/)

**Comment by nhsz** [comment]
Yep, [Node Hero tutorials](https://blog.risingstack.com/node-hero-tutorial-getting-started-with-node-js/) from RisingStack are good
