### ISSUE TITLE
best path for learning android

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#504]
Take a look [here](https://my.mindnode.com/9GNqw9qRvvg1A8Jeo9EW7fm8bcyWWtjKD6i6pa6w).

If you think there is a better way one can learn android or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on android that are missing or you wish something was added, you can say it here.

**Comment by burnett-ghartey** [comment]
https://github.com/yongjhih/awesome-android-awesomeness/blob/master/README.md
great curated resource

**Comment by nikitavoloboev** [comment]
Thank you @burnett-ghartey. I've [added it](https://my.mindnode.com/9GNqw9qRvvg1A8Jeo9EW7fm8bcyWWtjKD6i6pa6w). :)

**Comment by sreenivasanac** [comment]
https://github.com/anirudh24seven/android-dev-readme
Maybe we can add best links from this link or from the awesomeness link

**Comment by nikitavoloboev** [comment]
Yeah I have added it. Thank yu @sreenivasanac :)

**Comment by pateljay0323** [comment]
Please add [XAMARIN](https://www.xamarin.com/)

**Comment by SbyXlmm** [comment]
please add me
