### ISSUE TITLE
best path for learning music

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#506]
Take a look [here](https://my.mindnode.com/s7pJzgtWzzkz8ubfSzWxWyvuReC7eLVSHZqc4aRV).

If you think there is a better way one can learn music or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on music that are missing or you wish something was added, you can say it here.

**Comment by Mister-GoodwinLu** [comment]
Hooktheory isn't super amazing, but it helps knowing about chord progressions and tells you the chords that go with a song
