### ISSUE TITLE
best path for learning calculus

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#509]
Take a look [here](https://my.mindnode.com/rzNXGzaSkyjn634xxnSb2jwzC7wddoxxxrB91PwA).

If you think there is a better way one can learn calculus or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on calculus that are missing or you wish something was added, you can say it here.

**Comment by xSeanliux** [comment]
For the book, Calculus by Spivak, here's a good PDF file instead of the one you have. In the future, you might have a lot of books of the same name, 'Calculus', so you'd want to name tha author as well.

**Comment by nikitavoloboev** [comment]
Thank you a lot @xSeanliux. I have added it. You are right, we will need to differentiate books better.
