### ISSUE TITLE
best path for learning deep learning

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#510]
Take a look [here](https://my.mindnode.com/wqhKt6rDSZrJR5pVV2TpCv4xnHUsYJf3vZ9SbX7D).

If you think there is a better way one can learn deep learning or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on deep learning that are missing or you wish something was added, you can say it here.

**Comment by shotgunner** [comment]
[book about neural network and deep learning](http://neuralnetworksanddeeplearning.com)

**Comment by nikitavoloboev** [comment]
It's actually already in machine learning map but will move it here. :) 

Thank you @shotgunner 💙

**Comment by mrdougwright** [comment]
![https://www.manning.com/books/grokking-deep-learning](Grokking Deep Learning)

**Comment by nikitavoloboev** [comment]
Thank you @mrdougwright. Looks like an awesome book. I have added it. 💙

**Comment by anishsingh20** [comment]
Hii @nikitavoloboev  , below are some articles written by me on Medium related to deep learning fundamentals and some important concepts related to them which are the basics of Deep learning .
So i would definately like to add them in you amazing application.What do you think??
 
What are Activation Functions--[https://medium.com/towards-data-science/activation-functions-and-its-types-which-is-better-a9a5310cc8f ](url)

Optimization Algorithms used in Neural Networks--[https://medium.com/towards-data-science/types-of-optimization-algorithms-used-in-neural-networks-and-ways-to-optimize-gradient-95ae5d39529f](url)

Generative Models and GANs--[https://medium.com/towards-data-science/generative-models-and-gans-fe7efc20020b](url)

**Comment by nikitavoloboev** [comment]
Added all 3 of the articles. Thank you a lot @anishsingh20 💙

They will be up very soon with our new update.

**Comment by anishsingh20** [comment]
Thanks a lot @nikitavoloboev  , keep up the good work. Looking forward to adding much more educational resources and contributing in your amazing Project.
