### ISSUE TITLE
best path for learning go programming language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#511]
Take a look [here](https://my.mindnode.com/qpLq1TfqPWmu9sszrCxEM4QsWUH547TLNQkyfTyQ).

If you think there is a better way one can learn go or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on go that are missing or you wish something was added, you can say it here.

**Comment by whiteisthenewblack** [comment]
I really liked [The Little Go Book](http://openmymind.net/The-Little-Go-Book/), it's a very quick introduction which gets you started writing code

**Comment by nikitavoloboev** [comment]
Thank you @whiteisthenewblack. I have added it. Will be up shortly. 💙
