### ISSUE TITLE
best path for learning javascript

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#513]
Take a look [here](https://my.mindnode.com/QQzCynmUtZpAuyGipqxsvRJ6NPn477o9cSjCGqqR).

If you think there is a better way one can learn javascript or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on javascript that are missing or you wish something was added, you can say it here.

**Comment by hongDevCode** [comment]
I think you should look into adding Gordan Zhu's course on Practical Javascript on Watchandcode.com I like the way he explains why we need a specific function and how we use strings, numbers, function, booleans in a practical and real world manner.

**Comment by nikitavoloboev** [comment]
Added it. Thank you @hongDevCode 💙

**Comment by ParaBolt** [comment]
https://www.quirksmode.org/js/contents.html
