### ISSUE TITLE
best path for learning data structures

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#515]
Take a look [here](https://my.mindnode.com/2qFq7j3eSx2Szz3PcKGTbsSbM6psoYYGTErdyYXd).

If you think there is a better way one can learn data structures or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on data structures that are missing or you wish something was added, you can say it here.

**Comment by japjeet26** [comment]
berkeley lecture notes no tes no longer available

**Comment by nikitavoloboev** [comment]
What do you mean @japjeet26. The lectures [are up](https://www.youtube.com/watch?v=QMV45tHCYNI&list=PL4BBB74C7D2A1049C), no?

**Comment by japjeet26** [comment]
berkeley is taking away its free video lectures content . process initiated
on 15th April 2017. You can hava a look ... some lectures are already gone.
