### ISSUE TITLE
best path for learning programming language theory

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#519]
Take a look [here](https://my.mindnode.com/6GZfjhTKw6cscXsr3MqFCLAfPnCs9dEEWSAuptrR).

If you think there is a better way one can learn programming language theory or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on programming language theory that are missing or you wish something was added, you can say it here.

**Comment by zhengqunkoo** [comment]
[This resource](http://purelytheoretical.com/sywtltt.html) by Darryl McAdams provides a path on its own, I'm learning it in the next few months, so currently unsure of the quality, but it looks good so far!

**Comment by nikitavoloboev** [comment]
Thank you a lot @zhengqunkoo. I have added this resource to [Type Theory](https://learn-anything.xyz/mathematics/type_theory).

**Comment by zhengqunkoo** [comment]
The domain has closed. Both [it is archived](https://web.archive.org/web/20170615003229/http://purelytheoretical.com:80/sywtltt.html). All external links in the article are fine. Two internal links are broken, but both are archived:

1. [So you want to write a type checker](https://web.archive.org/web/20171220024154/http://languagengine.co/blog/so-you-want-to-write-a-type-checker/)
2. [ATCHC.pdf](https://web.archive.org/web/20170118222353/www.purelytheoretical.com/papers/ATCHC.pdf)
