### ISSUE TITLE
best path for learning regular expressions

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#520]
Take a look [here](https://my.mindnode.com/reBzaM1mn6WWuTM5iRAtrC1o7LzWBNwspT9pxNT3).

If you think there is a better way one can learn regular expressions or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on regular expressions that are missing or you wish something was added, you can say it here.

**Comment by whiteisthenewblack** [comment]
It's extremely dense, but [Mastering Regular Expressions](http://www.goodreads.com/book/show/583628.Mastering_Regular_Expressions) goes into meticulous detail about different regex implementations.

**Comment by nikitavoloboev** [comment]
Thank you @whiteisthenewblack. I have added it. Will be u shortly. 💙
