### ISSUE TITLE
best path for learning programming language design

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#522]
Take a look [here](https://my.mindnode.com/DGpMF54UqFrrurzbs77HTzyq8HswHBEwq8xdg8hB).

If you think there is a better way one can learn programming language design or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on programming language design that are missing or you wish something was added, you can say it here.

**Comment by kirillDanshin** [comment]
@nikitavoloboev add links from https://github.com/aalhour/awesome-compilers

**Comment by nikitavoloboev** [comment]
Hey @kirillDanshin, thank you. I have added them. I actually had awesome compilers already added to [compilers](https://my.mindnode.com/8zoz2iumK52ZVSsuEr2bqY2cyzpx7icMS1nMsNH1#203.8,-221.8,4). :)
