### ISSUE TITLE
best path for learning how to prepare for programming interview

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#525]
Take a look [here](https://my.mindnode.com/XSoat9hfA9vpEu9LsEStbuAzNWhPHZqDyh24sRzv).

If you think there is a better way one can learn programming interviews or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on programming interviews that are missing or you wish something was added, you can say it here.

**Comment by humford** [comment]
Hey @nikitavoloboev, I think this repository should be added under "prepare": https://github.com/andreis/interview.

**Comment by nikitavoloboev** [comment]
I have added it. Thank you.
