### ISSUE TITLE
best path for learning perl programming language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#529]
Take a look [here](https://my.mindnode.com/4XCVExihWLgHvFxnJZyxLMYWWt8rfsgi4Hrqykya).

If you think there is a better way one can learn perl or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on perl that are missing or you wish something was added, you can say it here.

**Comment by whiteisthenewblack** [comment]
You should definitely include Modern Perl. The ebook is free: http://modernperlbooks.com/books/modern_perl_2016/index.html

**Comment by nikitavoloboev** [comment]
Thank you @whiteisthenewblack. I have added it. Will be up shortly. 💙
