### ISSUE TITLE
best path for learning nim programming language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#531]
Take a look [here](https://my.mindnode.com/h8VJGBSS26e4bB4WdUx3myyoUczihJtvzGGj8whg).

If you think there is a better way one can learn nim or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on nim that are missing or you wish something was added, you can say it here.

**Comment by konqoro** [comment]
Blogs:
https://hookrace.net/blog/nim/
Rosetta code:
http://rosettacode.org/wiki/Category:Nim
Basics:
https://nim-lang.org/docs/manual.html
https://learnxinyminutes.com/docs/nim/
http://nim-by-example.github.io/
Books:
https://manning.com/books/nim-in-action?a_aid=niminaction&a_bid=78a27e81

**Comment by nikitavoloboev** [comment]
Added it. Thank you @konqoro
