### ISSUE TITLE
best path for learning ruby programming language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#533]
Take a look [here](https://my.mindnode.com/tjqqGCFLZbqp4sEDZqv7H6DB5Xwx7FUjhDdpBnit).

If you think there is a better way one can learn ruby or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on ruby that are missing or you wish something was added, you can say it here.

**Comment by lujanfernaud** [comment]
Some more resources.

## Guides

- [Codecademy](https://www.codecademy.com/learn/ruby)
- [Learn to Program](https://pine.fm/LearnToProgram)
- [Learn Ruby The Hard Way](https://learnrubythehardway.org/book/)
- [Community Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide)

## Practice

- [exercism.io](http://exercism.io/)
- [Ruby Quiz](http://rubyquiz.com/)
- [Codewars](https://www.codewars.com)
- [CodinGame](https://www.codingame.com)

## Frameworks

- [Hanami](http://hanamirb.org/)
- [Roda](http://roda.jeremyevans.net/index.html)
- [Cuba](https://github.com/soveran/cuba)

## Newsletters

- [Ruby Weekly](http://rubyweekly.com/)
- [RubyLetter](http://www.rubyletter.com/)

## Aggregators

- [Rubyland](http://rubyland.news/)
- [RubyFlow](http://www.rubyflow.com/)

**Comment by nikitavoloboev** [comment]
Thank you a lot @lujanfernaud, will add them now. 💙

**Comment by lujanfernaud** [comment]
Congrats on the project @nikitavoloboev.

**Comment by KaraAJC** [comment]
Just adding [Minitest](https://rubygems.org/gems/minitest/versions/5.8.4) as another testing framework for ruby

**Comment by joren** [comment]
Could you add http://hanamirb.org to the web frameworks?

**Comment by nikitavoloboev** [comment]
Added it. Thank you @joren
