### ISSUE TITLE
best path for learning kotlin programming language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#534]
Take a look [here](https://my.mindnode.com/5LipbLiRfryhTsqRL6za1x5qzpQBh3mmD997Kwvb).

If you think there is a better way one can learn kotlin or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on kotlin that are missing or you wish something was added, you can say it here.

**Comment by FahadMk** [comment]
the way you present is so cool i guess you can add like a community that is related to kotlin where they can easily interact with other or some tutorial videos it will lot cooler if you could actually do that .
