### ISSUE TITLE
best path for learning swift programming language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#536]
Take a look [here](https://my.mindnode.com/vAJcWyzzTubpywgp8o367gPWvRUxi2y5r2sZMryb).

If you think there is a better way one can learn swift or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on swift that are missing or you wish something was added, you can say it here.

**Comment by NickToda** [comment]
Not spamming or advertising this, but Chris Lattner the creator of Swift recommends this site: https://www.hackingwithswift.com/#about
