### ISSUE TITLE
best path for learning rust programming language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#537]
Take a look [here](https://my.mindnode.com/7Q14XaYLnco9X1oqfouxpibjMz3Asy6PVDjf8C3Y#52.2,-114.2,2).

If you think there is a better way one can learn rust or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on rust that are missing or you wish something was added, you can say it here.

**Comment by jordanlhenderson** [comment]
While you are looking into other resources, you can take advantage of [this podcast ](http://www.newrustacean.com/) at times when listening is more convenient than reading.   Chris does a great job explaining some concepts and provides lots of news and pointers.

**Comment by nikitavoloboev** [comment]
Oh thank you @jordanlhenderson, I 💙 podcasts. Will add it too. :)
