### ISSUE TITLE
best path for learning elixir programming language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#538]
Take a look [here](https://my.mindnode.com/zW4mZpEwWk59LkRXCFQCxLCNGp52Uzt9yHFyk7A3#93.5,-185.3,2).

If you think there is a better way one can learn elixir or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on elixir that are missing or you wish something was added, you can say it here.

**Comment by agustif** [comment]
I wish some good elixir resources were added

## General Stuff
http://jobs.elixirdose.com/
hex.pm - Elixir Package Manager
hexdocs.pm - Elixir Docs * Note, recently elixir-lang is moving all it's docs to hexdocs
elixirschool.com - Elixir Community Curated Guides
https://www.dailydrip.com/topics/elixir
www.phoenixframework.org
elixre.uk
## Forum
elixirforum.com - Elixir Community running on Discourse

## News
elixirstatus.com
https://www.reddit.com/r/elixir/

## Newsletters
elixirweekly.com
https://elixir.libhunt.com
http://plataformatec.com.br/elixir-radar/





## Blogs
https://medium.com/tag/phoenix-framework
https://medium.com/tag/elixir
https://medium.com/tag/ecto
http://blog.plataformatec.com.br/tag/elixir/

https://dockyard.com/blog/categories/ecto
https://dockyard.com/blog/categories/phoenix
https://dockyard.com/blog/categories/elixir

http://michal.muskala.eu/tag/elixir.html

## Elixir a XYZ Perspective
Haskell -
 https://docs.google.com/presentation/d/13RkIOWUjEsGOKXpnsFnKfunzAovyQ5TKdbw1l5WHWv0/
JS/PHP - https://ryanwinchester.ca/posts/intro-to-elixir-for-non-ruby-programmers

## Elixir VS XYZ
Ruby - https://hmans.io/posts/2017/05/24/elixir-phoenix-use-cases.html

## Books
https://shankardevy.com/phoenix-book/

**Comment by nikitavoloboev** [comment]
Thank you so much @agustif. I have [added quite a lot of it](https://my.mindnode.com/zW4mZpEwWk59LkRXCFQCxLCNGp52Uzt9yHFyk7A3).

**Comment by agustif** [comment]
elixirforum is really great, a lot of not-so techincal stuff moved from google mail lists from elixir-lang to the elixirforum, a lot of core-team members and libraries developers and book authors are active there too

**Comment by agustif** [comment]
I've been pondering the last months to build an specific aggregator on elixir-related-stuff, I already consume a lot of it so making parsers and RSS scrapers wouldn't be that hard, The reasoning is if I can do a 20% of the content, putting it online and with 5 people like me would make a complete elixir resource center (I want to index, scrap and relate stuff, from official docs to blogposts and youtube videos.

A lot of stuff derives from other stuff, so having it all play nice in an UI would it make easier to just code and lookup what you need to know in that specific moment in time.

**Comment by natecox** [comment]
A few resources that I've found which are really helpful:

# Books
## Elixir Generic
https://pragprog.com/book/elixir13/programming-elixir-1-3
https://pragprog.com/book/lhelph/functional-web-development-with-elixir-otp-and-phoenix
https://pragprog.com/book/cmelixir/metaprogramming-elixir

## Phoenix
https://pragprog.com/book/phoenix/programming-phoenix

# Online Guides/Tools
## Elixir Generic
http://exercism.io/languages/elixir/about

## Phoenix
https://learnphoenix.io

**Comment by nikitavoloboev** [comment]
Thank you @natecox. I have added them. Will be up shortly. 💙
