### ISSUE TITLE
best path for learning clojure programming language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#540]
Take a look [here](https://my.mindnode.com/q3CqTsNEX43ovcxU9qoYU3wn23Fro7qbWaqxFULX).

If you think there is a better way one can learn android or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on android that are missing or you wish something was added, you can say it here.

**Comment by irasantiago** [comment]
Hey! I'm currently learning clojure and here are some resources I've found useful so far (many of them can be found in this article: https://notamonadtutorial.com/how-to-earn-your-clojure-white-belt-7e7db68a71e5):

Exercises/Code challenges: 
http://clojurescriptkoans.com/
http://www.4clojure.com/problems

Online book: 
http://www.braveclojure.com/foreword/

**Comment by nikitavoloboev** [comment]
Hey @irasantiago. Thank you a lot. I have added them. Will be u shortly. 💙
