### ISSUE TITLE
best path for learning smalltalk programming language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#545]
Take a look [here](https://my.mindnode.com/rv35EzC72HtQBmAse2k9WgxyssY4qTbs2u3FU9ux).

If you think there is a better way one can learn smalltalk or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on smalltalk that are missing or you wish something was added, you can say it here.

**Comment by codeZeilen** [comment]
I would like to suggest some additional resources, as the current collection is pretty focused on GNU Smalltalk which only represents one style of Smalltalk. In particular, in contrast to GNU Smalltalk most other Smalltalk implementations come with a graphical interactive development environment. Therefore, I would suggest adding resources on the Squeak Smalltalk environment (the home of EToys and early versions of Scratch):

https://www.hpi.uni-potsdam.de/hirschfeld/trac/SqueakCommunityProjects/wiki/squeak_screencasts
https://www.hpi.uni-potsdam.de/hirschfeld/trac/SqueakCommunityProjects/wiki/smalltalk_koans

Additionally, I would suggest the following article on the philosophy of Smalltalk which illustrates the mindset very well:

https://www.cs.virginia.edu/~evans/cs655/readings/smalltalk.html

**Comment by nikitavoloboev** [comment]
Added it. Thank you @codeZeilen
