### ISSUE TITLE
best path for learning vue.js

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#551]
Take a look [here](https://my.mindnode.com/nGBJtTf4DYUj4sxXXZRBn7YkRnxb1LtqLmzhonLn#-70.3,-28.1,2).

If you think there is a better way one can learn vue.js or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on vue.js that are missing or you wish something was added, you can say it here.

**Comment by Splode** [comment]
I found the official Vue.js forum to be very helpful when learning Vue.js [https://forum.vuejs.org/](https://forum.vuejs.org/)

**Comment by nikitavoloboev** [comment]
Added it. Thank you @Splode

**Comment by KayvanMazaheri** [comment]
There is a great video series on Vue 2 that deserves to be here.
[VueCasts.com](http://vuecasts.com)

**Comment by nikitavoloboev** [comment]
Added it. Thank you @KayvanMazaheri

**Comment by phiwut** [comment]
There is an huge Github repo with all the official Resources for Vue.js: [https://github.com/vuejs/awesome-vue](https://github.com/vuejs/awesome-vue)
