### ISSUE TITLE
best path for learning jQuery

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#552]
Take a look [here](https://my.mindnode.com/Gr8yvuKJCWgjaeJXoiUudYqoid8oeky6b81Cwunf#34.7,-47.4,2).

If you think there is a better way one can learn jQuery or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on jQuery that are missing or you wish something was added, you can say it here.

**Comment by prabinzz** [comment]
I think [w3school](https://www.w3schools.com/jquery/) branch should be added in the basics branch. Their way of teaching is effective for beginers.

**Comment by nikitavoloboev** [comment]
Added it. Thank you @prabinzz
