### ISSUE TITLE
best path for learning electron

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#554]
Take a look [here](https://my.mindnode.com/1Gr5QZ6ycqVbhVNahBk6qjdSjsttzxuCz3UVDge1#-101.2,-205.9,2).

If you think there is a better way one can learn electron or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on electron that are missing or you wish something was added, you can say it here.

**Comment by Tynael** [comment]
I have wrote a step-by-step guide for beginners on how to create a simple app with Electron.

If you find this resource useful, please consider adding it to the roadmap:

https://neutrondev.com/how-build-first-app-electron/

**Comment by nikitavoloboev** [comment]
Thank you @Tynael. I [have added it](https://learn-anything.xyz/web_development/javascript_libraries/electron). 💙

**Comment by Tynael** [comment]
Thanks a lot, guys!
