### ISSUE TITLE
best path for learning full stack development

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#556]
Take a look [here](https://my.mindnode.com/YfXtXRQ4Vys8SZaxwKETATNSWX4rbhHeq6xPxLjm#300.2,-94.6,1).

If you think there is a better way one can learn full stack development or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on full stack development that are missing or you wish something was added, you can say it here.

**Comment by chandar18** [comment]
Ruby on Rails can be included as a Full stack Development

**Comment by nikitavoloboev** [comment]
Added it. Thank you @chandar18 :)

**Comment by Martinnord** [comment]
Nothing shows when pressing AngularJS
