### ISSUE TITLE
best path for learning emacs text editor

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#558]
Take a look [here](https://my.mindnode.com/GQPbqm3QBqQrp8Pzz1kcYFQsDqMppMHkdH84y3bR).

If you think there is a better way one can learn emacs or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on emacs that are missing or you wish something was added, you can say it here.

**Comment by guylyons** [comment]
Could this be added as a 'Getting Started,' perhaps? http://ergoemacs.org/emacs/emacs.html
Very good resource for people dipping their toes into Emacs.

**Comment by nikitavoloboev** [comment]
Thank you @guylyons, I have added it. 💙
