### ISSUE TITLE
best path for learning vim text editor

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#559]
Take a look [here](https://my.mindnode.com/onsumXxs7xywXeQxDHEJxfM8pQ5YNxmfzfxQc74T).

If you think there is a better way one can learn vim or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on vim that are missing or you wish something was added, you can say it here.

**Comment by shotgunner** [comment]
[interactive vim tutorial](http://openvim.com/)

**Comment by nikitavoloboev** [comment]
Thank you @shotgunner, I've added it 💙
