### ISSUE TITLE
best path for learning linux distributions

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#570]
Take a look [here](https://my.mindnode.com/uZFAizZuJGxuAr4s2XYQ3vCLsUELCqLzL8XpzmxY).

If you think there is a better way one can learn linux distributions or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on linux distributions that are missing or you wish something was added, you can say it here.

**Comment by Astumed** [comment]
You should use the https://github.com/FabioLolix/LinuxTimeline and https://distrowatch.com for the list and documentation about linux distributions

**Comment by nikitavoloboev** [comment]
Thank you @Astumed. I will add them. :)
