### ISSUE TITLE
best path for learning ethereum

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#573]
Take a look [here](https://my.mindnode.com/Qzw4xRpZJLXCBG357zegCse43zFFzkBmssmg78Bo#-45.3,-253.9,2).

If you think there is a better way one can learn ethereum or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on ethereum that are missing or you wish something was added, you can say it here.

**Comment by Katamori** [comment]
Question: shouldn't you connect related topics like blockchain - e.g. for the "basics" section?

**Comment by nikitavoloboev** [comment]
Hey @Katamori. We will add prerequisite knowledge to each map in a similar way [shown here](https://github.com/learn-anything/search-engine/issues/30). So this problem will be solved. :)

**Comment by Katamori** [comment]
Oh, cool!

Until that I'd suggets an additional source to the map: [Ethereum has its Stack Exchange site, as well.](https://ethereum.stackexchange.com/)

Currently I'm busy, so can't really fork, make on my own, and make a pull request, but during the week, I may produce addition of links like this if you approve it.

**Comment by nikitavoloboev** [comment]
Yeah certainly. Although the forking of maps is still not added. But will be soon.

**Comment by Katamori** [comment]
Sure, I missed for a moment the fact that the source of the site isn't in the repo so far.
