### ISSUE TITLE
best path for learning unity game engine

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#574]
Take a look [here](https://my.mindnode.com/e6eGCsYMysgfLWp32sC94KKjriUy5UNmBJXJGoox#71.2,-295.0,2).

If you think there is a better way one can learn unity or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on unity that are missing or you wish something was added, you can say it here.

**Comment by lulucca12** [comment]
There's a great youtube channel you could add, his name is GameGrind and he is very good: [https://www.youtube.com/channel/UCTY3kks3U4RDvpMX87fvo1A](url)
