### ISSUE TITLE
best path for learning russian language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#582]
Take a look [here](https://my.mindnode.com/4eQcjH3g5sypLz42tryUQ49NZzfhE3Crb4m9tq1v#-9.2,-87.8,2).

If you think there is a better way one can learn russian language or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on russian language that are missing or you wish something was added, you can say it here.

**Comment by finnoleary** [comment]
Memrise is good, so is Michael Thomas' Russian course -- although that is expensive. I've found Anki useful to solidify information from those sources.
