### ISSUE TITLE
best path for learning english language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#583]
Take a look [here](https://my.mindnode.com/oTrSaQmHmUvsfe1y2CpKU4xxnXueJKpKGoyWLZ68).

If you think there is a better way one can learn english language or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on english language that are missing or you wish something was added, you can say it here.

**Comment by meldm** [comment]
Hi!
This is another good site [http://learnamericanenglishonline.com/](http://learnamericanenglishonline.com/)
for learning English.

**Comment by nikitavoloboev** [comment]
Thank you @meldm, I have [added it](https://my.mindnode.com/oTrSaQmHmUvsfe1y2CpKU4xxnXueJKpKGoyWLZ68). :)

**Comment by lujanfernaud** [comment]
[Clozemaster](https://www.clozemaster.com) is a fantastic resource to learn English and [many other languages](https://www.clozemaster.com/languages).

**Comment by nikitavoloboev** [comment]
Thank you a lot @lujanfernaud. I have added it. 💙
