### ISSUE TITLE
best path for learning IPFS

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#593]
Take a look [here](https://my.mindnode.com/Hsex87wcsZbzbwMNzbaJFsBPFJycLymJqA7sotvg).

If you think there is a better way one can learn IPFS or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on IPFS that are missing or you wish something was added, you can say it here.

**Comment by Katamori** [comment]
* [Official website](https://ipfs.io/) with lotsa documentations and explanations.

* [Central IPFS discussion board](https://discuss.ipfs.io/)

* [Subreddit](https://www.reddit.com/r/ipfs/)
