### ISSUE TITLE
best path for learning redis

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#598]
Take a look [here](https://my.mindnode.com/Fb7dmtCvahWRF1LWybq5JqtPjHwBeF4mxoV7zLB5#9.5,-25.4,2).

If you think there is a better way one can learn redis or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on redis that are missing or you wish something was added, you can say it here.

**Comment by truongminh** [comment]
Redis has really brought about some novel idea.
But I think it should be categorized as a NoSQL learning map.
