### ISSUE TITLE
best path for learning relational databases

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#599]
Take a look [here](https://my.mindnode.com/y48JgLrYtbyNrsKyRze4WHzhYVrGZks9N9pvsekp#-72.8,-182.5,2).

If you think there is a better way one can learn relational databases or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on relational databases that are missing or you wish something was added, you can say it here.

**Comment by Mackaber** [comment]
I don't think the provided link is a good place to start with RDB, it barely explains how it works internally but not how to use it..., I propose a better article to get started with this --> https://www.ntu.edu.sg/home/ehchua/programming/sql/Relational_Database_Design.html

**Comment by nikitavoloboev** [comment]
Thank you @Mackaber. You are right. I have changed it.
