### ISSUE TITLE
best path for learning linear algebra

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#609]
Take a look [here](https://my.mindnode.com/9GQnwWMBYXMe1XjUD8G21qpxiyz5B4MraPtL8xyy#107.0,46.1,2).

If you think there is a better way one can learn linear algebra or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on linear algebra that are missing or you wish something was added, you can say it here.

**Comment by hafager** [comment]
This page has some great examples of the applications of linear algebra. This is great to really understand how it can be applied in different scenarios.

http://aix1.uottawa.ca/~jkhoury/app.htm

**Comment by nikitavoloboev** [comment]
Added it. Thank you @hafager
