### ISSUE TITLE
best path for learning type theory

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#611]
Take a look [here](https://my.mindnode.com/eytyqpDLBmrC4xVnHCDqRVBZi39xhXBWnBRSTVoM#272.1,61.8,2).

If you think there is a better way one can learn type theory or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on type theory that are missing or you wish something was added, you can say it here.

**Comment by chamini2** [comment]
- Set theory
- Russel's paradox
- Which leads to type theory as a solution to the paradox
- intuitionistic type theory
- dependent type theory
- Curry-Howard correspondence

**Comment by nikitavoloboev** [comment]
Very interesting. Thank you a lot @chamini2 

I have added this. Will be up very soon. 💙

Would really love to hear how more I can improve these maps in these areas as its a subject I am deeply fascinated with.
