### ISSUE TITLE
best path for learning logic

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#612]
Take a look [here](https://my.mindnode.com/1GGWUw7yg9oqPVsqx83FwnMa41ecAcYXYJp5GRRR#51.0,4.8,2).

If you think there is a better way one can learn logic or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on logic that are missing or you wish something was added, you can say it here.

**Comment by RoshnaOmer** [comment]
I don't think there is anything wrong with it, but the nodes are overlapped and I couldn't read the one that is under Proof Theory, so can we add moving nodes around or no?

**Comment by nikitavoloboev** [comment]
Yes, users will be able to move around and propose changes to the mind maps very soon. :)
