### ISSUE TITLE
best path for learning neural networks

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#624]
Take a look [here](https://my.mindnode.com/VznvpXy4JfeyVL4toshCQE3pdyHvLzx1bTGUpze2#204.2,151.7,2).

If you think there is a better way one can learn neural networks or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on neural networks that are missing or you wish something was added, you can say it here.

**Comment by goxul** [comment]
https://www.youtube.com/watch?v=bxe2T-V8XRs&list=PLiaHhY2iBX9hdHaRr6b7XevZtgZRa1PoU

This is a good beginner resource for neural nets.
