### ISSUE TITLE
best path for learning machine learning libraries

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#626]
Take a look [here](https://my.mindnode.com/PVcz8iqUfa941KTpBqXgpiP7Asst1yGcqVa8Kmit#-179.6,-220.0,2).

If you think there is a better way one can learn machine learning libraries or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really great machine learning libraries that are missing or you wish something else was added, you can say it here.

**Comment by izdi** [comment]
Hey, great project!
There is no brainer framework one should consider learning ML or using improving business operations with: 
https://github.com/scikit-learn/scikit-learn

**Comment by nikitavoloboev** [comment]
Thank you a lot @izdi. I have added [scikit](https://my.mindnode.com/35hVLCpp3wbpsx4YqVD9XxpczbpPpyWJjwWfsfAq) to [libraries](https://my.mindnode.com/PVcz8iqUfa941KTpBqXgpiP7Asst1yGcqVa8Kmit). Glad you like the project. 💚
