### ISSUE TITLE
best path for learning graphic design

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#631]
Take a look [here](https://my.mindnode.com/3LqqYjEYQWQsrSk3Ypvy193fTspqZuiCy4emM7Bz#26.9,-36.9,2).

If you think there is a better way one can learn graphic design or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on graphic design that are missing or you wish something was added, you can say it here.

**Comment by iambigi** [comment]
Hello, 
You should also add Adobe Illustrator and Corel to the Graphic Design node, Photoshop being more in the (but not limited to) artistic part while graphic design aims more for problem solving.

A while back started a project called "A designer's database" where I add tutorials, resources and other helpful links to articles found online, while the spreadsheet has Photoshop/Illustrator separated pages. Anyone is welcomed to add helpful links.
Here's the link: https://goo.gl/zfIdJE

**Comment by Malestratz** [comment]
there's a coursere.org specialization on graphic design, and also lynda.com offer nice courses

**Comment by nikitavoloboev** [comment]
Thank you @Malestratz and @iambigi, I've added them

**Comment by Malestratz** [comment]
You're welcome :)
