### ISSUE TITLE
best path for learning LaTeX

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#635]
Take a look [here](https://my.mindnode.com/4bwpnfgzEsxWdzsbgDzUJdK8qxmvEKEK8tdWPmD5).

If you think there is a better way one can learn LaTeX or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on LaTeX that are missing or you wish something was added, you can say it here.

**Comment by Katamori** [comment]
Theoretically [it's a great tutorial material](https://www.latex-tutorial.com/tutorials/) for beginners and as an introduction to LaTeX.

**Comment by nikitavoloboev** [comment]
Thats awesome. Thank you @Katamori
