### ISSUE TITLE
best path for learning user experience

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#636]
Take a look [here](https://my.mindnode.com/HxHcbJzNjqT4s8esfDyUQYEACFDysxTx43FUGdYx).

If you think there is a better way one can learn user experience or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on user experience that are missing or you wish something was added, you can say it here.

**Comment by joakimc** [comment]
Hey, here's a couple of nice UX-sources:

- https://www.nickkolenda.com/user-experience/
- https://uxdesign.cc/ux-design-methods-deliverables-657f54ce3c7d

**Comment by nikitavoloboev** [comment]
Hey @joakimc. Thank you so much for these. I have [added them](https://my.mindnode.com/HxHcbJzNjqT4s8esfDyUQYEACFDysxTx43FUGdYx). :)

**Comment by Kaivosukeltaja** [comment]
Hi! Maybe there should be a list of the various disciplines used in UX design, such as interaction design, task analysis, information architecture and user research? Realizing the existence of these brough my level of UX understanding from "it's just making educated guesses" to "there's a ton of tools and techniques to use". This is the article that lit my light bulb: https://medium.com/@uxmuch/ten-skills-you-need-to-be-a-ux-unicorn-f7ec555981b0

**Comment by nikitavoloboev** [comment]
Thank you @Kaivosukeltaja, I have added them. I may split user experience into more mind maps further I think. User-Cantered design seems like an interesting topic.

**Comment by lakshit1001** [comment]
http://www.useronboard.com/onboarding-teardowns/
