### ISSUE TITLE
best path for learning classical mechanics

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#640]
Take a look [here](https://my.mindnode.com/Xs5qLyzR293qpAZLJWY39SuvK2xkW2YxWm61wT2M#98.1,-60.1,4).

If you think there is a better way one can learn classical mechanics or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on classical mechanics that are missing or you wish something was added, you can say it here.

**Comment by lulucca12** [comment]
there are a site and a free ebook that says much about classical mechanics and physics, the ebook is: [http://www.physics.rutgers.edu/ugrad/494/bookr03D.pdf](url) and the site: [http://torassa.tripod.com/paper.htm](url).

**Comment by nikitavoloboev** [comment]
Hey @lulucca12, I have added it. Thank you. 💙

**Comment by lulucca12** [comment]
And I would like to add some paid books: Mathematics of Classical and Quantum Physics: [https://www.amazon.com/Mathematics-Classical-Quantum-Physics-Dover/dp/048667164X/keywords=Mathematics+of+Classical+and+Quantum+Physics](url), Classical Mechanics by John R. Taylor: [https://www.amazon.com/Classical-Mechanics-John-R-Taylor/dp/189138922X/keywords=Classical+Mechanics+taylor](url) and Intrudution to Classical Mechanics: [https://www.amazon.com/Introduction-Classical-Mechanics-Problems-Solutions/dp/0521876222/keywords=Introduction+to+Classical+Mechanics&linkCode=sl1](url)

**Comment by nikitavoloboev** [comment]
Thank you @lulucca12. I have added them too. ˅
