### ISSUE TITLE
best path for learning quantum mechanics

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#641]
Take a look [here](https://my.mindnode.com/qJ23VQZs8r5YToae7Ch6Tein6h7U5yhAiw8enxsH#66.7,112.9,2).

If you think there is a better way one can learn quantum mechanics or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on quantum mechanics that are missing or you wish something was added, you can say it here.

**Comment by Yurlungur** [comment]
Quantum mechanics needs some background information on linear algebra (which is essential!), calculus, and Newtonian physics.

**Comment by nikitavoloboev** [comment]
Hey @Yurlungur, we plan to add requirements and recommendations very soon. Essentially nearly all maps will state what material is needed to learn the topic well and we will link to the mind maps to learn the topics too. :)

**Comment by Yurlungur** [comment]
Sure sounds good. :)
