### ISSUE TITLE
best path for learning quantum computing

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#642]
Take a look [here](https://my.mindnode.com/F8ubCrxApr7pFiW8TxvNyyzD51WqHkzVDFMN4cyp#263.6,-66.2,2).

If you think there is a better way one can learn quantum computing or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on quantum computing that are missing or you wish something was added, you can say it here.

**Comment by necro33** [comment]
You can add,
https://ocw.mit.edu/courses/mathematics/18-435j-quantum-computation-fall-2003/

**Comment by nikitavoloboev** [comment]
Thank you @necro33. This seems great, I have added it. Will be up shortly. :)
