### ISSUE TITLE
best path for learning guitar

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#644]
Take a look [here](https://my.mindnode.com/xPUGxGodprtehL3P5zd7dyzmTeaDYiCQxkVp8nrF).

If you think there is a better way one can learn guitar or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on guitar that are missing or you wish something was added, you can say it here.

**Comment by tdoskocil** [comment]
Have not had a chance to look at it but will soon. 



Sent from myMail for iOS


Sunday, May 14, 2017, 1:57 PM -0500 from Nikita Voloboev  <notifications@github.com>:

**Comment by Yashrocky96** [comment]
You could add references for Fingerstyle Learning for LickNRiff on youtube.

Add the intermediate courses from Justin Guitar too.

I love the mind map, the only thing it lacks is UI, the design is a bit on the low-end if that is fixed this could be a great education app for self learning anything.

**Comment by nikitavoloboev** [comment]
Thank you a lot @Yashrocky96. I [have added them](https://my.mindnode.com/xPUGxGodprtehL3P5zd7dyzmTeaDYiCQxkVp8nrF).

We are working on our own solution currently that would allow embedding these mind maps in the same page as the search. You can read more about it [here](https://ducksource.github.io). :)

Glad you like the mind maps.

**Comment by Blake575** [comment]
This is a great intro to guitar for people without a music theory background:
https://www.guitarforbeginners.com/

Then these two resources could go into a new fingerstyle section:
1. A how-to playlist on arranging fingerstyle arangements:
https://www.youtube.com/playlist?list=PLdF1zkcWxN_-Gy7jX4aflhNAo-IwGlvD6

2. Free fingerstyle lessons and tabs:
http://www.guitarnick.com/fingerstyle_and_fingerpicking_-_lessons_and_songs.html

**Comment by nikitavoloboev** [comment]
Added it. Thank you @Blake575
