### ISSUE TITLE
best path for learning nuclear power

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#648]
Take a look [here](https://my.mindnode.com/VsJNqTHszge5FaDgKQXk94U6mzvFT5dSHd5cRu1p#6.4,-40.8,2).

If you think there is a better way one can learn nuclear power or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on nuclear power that are missing or you wish something was added, you can say it here.

**Comment by nightwing38** [comment]
Stop

**Comment by nikitavoloboev** [comment]
You can unsubscribe from notifications @nightwing38

**Comment by Katamori** [comment]
Valuable, but casually speaking sources like Kurzgesagt should be marked with a different icon, to separate them from official, scientific sources.

Or at the very least, additional sources documented in such "casual sources" should be attached as "leaf nodes" to the parent.

It can diversify the list of available sources.

**Comment by nikitavoloboev** [comment]
I agree with you partly. Perhaps we can show multiple emojis for material? I fear there will be mental overload of trying to decipher all the emojis. I want to keep as simple as possible. 

We will add a way to add 'notes' to all nodes. Similar to how you can see [here](https://my.mindnode.com/ha8hqZuHbb5Py7LzxWoCatscK9AZsR93vJbyfqiq#218.8,36.2,2) which clicking on the note icon near coding theory. Perhaps that can solve this?

**Comment by Katamori** [comment]
Then you may consider using two ancestor branches like "official/scientific/professional" and "hobby/amateur/documentary" or something, and not only here.
