### ISSUE TITLE
best path for learning drugs

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#652]
Take a look [here](https://my.mindnode.com/5HyyfoE5sufZR5RvN9isTCdaYByzxFVhLqpk2MXg#-150.3,-186.9,2).

If you think there is a better way one can learn drugs or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on drugs that are missing or you wish something was added, you can say it here.

**Comment by mattdax** [comment]
Under stimulants I think adding amphetamines Wikipedia is a good start towards adding them. I would eventually recommend a page for amphetamines on their own

**Comment by nikitavoloboev** [comment]
Thank you @mattdax. I have added them. Will be u shortly. 💙

**Comment by patrickjrock** [comment]
Adding the following general categories would be a good start: autonomics, antimicrobials, antineoplastics, monoclonal antibodies/biologics. This section should probably also link to an article on pharmacology.

**Comment by nikitavoloboev** [comment]
Thank you @patrickjrock, I have added it. Will be up shortly.
