### ISSUE TITLE
best path for learning fitness

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#655]
Take a look [here](https://my.mindnode.com/Qruad21hxq43Qw4xHN4gyPZmeKc33cx3BDHq1o47#80.7,-153.6,2).

If you think there is a better way one can learn fitness or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on fitness that are missing or you wish something was added, you can say it here.

**Comment by timmy3131** [comment]
🌐[Iraki Nutrition：resources-to-keep-yourself-updated](http://www.irakinutrition.com/blog/resources-to-keep-yourself-updated/)
