### ISSUE TITLE
best path for learning redux library

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#667]
Take a look [here](https://my.mindnode.com/eD7tx71JUqC6R4iqaPGxzvdR2ocpqGq5TVsxp2yk).

If you think there is a better way one can learn redux library or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on redux library that are missing or you wish something was added, you can say it here.

**Comment by conradkay** [comment]
https://egghead.io/courses/getting-started-with-redux
https://egghead.io/courses/building-react-applications-with-idiomatic-redux
these two FREE courses are made by the creator of redux himself.

**Comment by nikitavoloboev** [comment]
Added it. Thank you @conradkay
