### ISSUE TITLE
best path for learning django library

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#668]
Take a look [here](https://my.mindnode.com/K5WJhHspfaaezNNbNRZYxWGEoofFqnQVTa3ZcxEz#14.7,311.9,2).

If you think there is a better way one can learn django or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on django that are missing or you wish something was added, you can say it here.

**Comment by jesseneal** [comment]
I would recommend adding [The Offical Django Tutorial](https://docs.djangoproject.com/en/1.11/intro/tutorial01/) to basics.

**Comment by nikitavoloboev** [comment]
Thank you @jesseneal, I added it.

**Comment by shotgunner** [comment]
good free online book for learning django => [django book](http://djangobook.com/)
Reusable Django apps, sites and tools directory => [django packages](djangopackages.org)
