### ISSUE TITLE
best path for learning docker

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#675]
Take a look [here](https://my.mindnode.com/mckfV3fnWaJJirpCTcieUhRdyMT3TuLHq6RY54Gs).

If you think there is a better way one can learn docker or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on docker that are missing or you wish something was added, you can say it here.

**Comment by shotgunner** [comment]
I think [katacoda.com](katacoda.com) have good interactive tutorials on docker. please add it.

**Comment by shotgunner** [comment]
Also [play-with-docker](http://labs.play-with-docker.com/) is good site for try docker with online console without install it on local computer (or server).

**Comment by nikitavoloboev** [comment]
Thank you @shotgunner, I have added them. :)

**Comment by Katamori** [comment]
[This article](http://blog.brew.com.hk/introduction-to-docker/) looks like a decent point of beginning.

**Comment by nikitavoloboev** [comment]
Added it. Thank you @Katamori
