### ISSUE TITLE
best path for learning aws

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#677]
Take a look [here](https://my.mindnode.com/TCxkEPQuB1ApGPDJT4RcsusD7JFkgNq4HjwAqbLj).

If you think there is a better way one can learn aws or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on aws that are missing or you wish something was added, you can say it here.

**Comment by rdp-cloud** [comment]
Hello Nikita,

I believe that the only "Articles" resource is not related to 'learning' about AWS. It is closer to 'propaganda' against AWS and thus not appropriate in such a forum.

Regards,

Rodney

**Comment by nikitavoloboev** [comment]
I agree with you @rdp-cloud. I have removed it. Thank you.
