### ISSUE TITLE
best path for learning c# programming language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#678]
Take a look [here](https://my.mindnode.com/6WmDpnHqF93PcBqtajq5Y2kFTy3HqyadWjazqqAU).

If you think there is a better way one can learn c# or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on c# that are missing or you wish something was added, you can say it here.

**Comment by 70MN3U** [comment]
C# Fundamentals for Absolute Beginners by Bob Tabor on Microsoft Virtual Academy is a great way to start. Currently doing the course myself.

Course can be found [here](https://mva.microsoft.com/en-us/training-courses/c-fundamentals-for-absolute-beginners-16169).

**Comment by nikitavoloboev** [comment]
Thank you @70MN3U, I have added it.

**Comment by vorou** [comment]
This free e-book on C# threading is gold:
http://www.albahari.com/threading/

**Comment by nikitavoloboev** [comment]
Added it. Thank you @vorou
