### ISSUE TITLE
best path for learning data science

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#681]
Take a look [here](https://my.mindnode.com/zxRG1oYfCw5DU8ExnRnyJt6qAWz9MM41sqhniGyv).

If you think there is a better way one can learn data science or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on data science that are missing or you wish something was added, you can say it here.

**Comment by shotgunner** [comment]
this site is not mentioned. I think it is useful : [data science ontology](http://datascienceontology.com)
