### ISSUE TITLE
best path for learning japanese language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#684]
Take a look [here](https://my.mindnode.com/F7y3iSAwZdzGnRRWLur3RpXiJviy1YF7QxZwDLxv).

If you think there is a better way one can learn japanese language or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on japanese language that are missing or you wish something was added, you can say it here.

**Comment by langdonjp** [comment]
I'd like to propose for [this guide](https://kumasensei.net/the-path-to-japanese-fluency/) to be added to the Japanese language map. It was written with self-learners in mind and was very well-received on the Learn Japanese subreddit, appealing to absolute beginners and advanced learners alike. The guide also includes links to other resources that pretty much cover all the bases of language learning (reading, writing, listening, and speaking).

**Comment by nikitavoloboev** [comment]
Thank you @langdonjp, I have added it. 💙

**Comment by Raufun** [comment]
I like to add [this guide](https://www.tofugu.com/) to the Japanese language map. This website covers almost everything from the Japanese language to Japanese culture, tradition and so on. Thank you!
