### ISSUE TITLE
best path for learning 3d.js library

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#685]
Take a look [here](https://my.mindnode.com/oABafsSirqHz4o8Nh4pLqwCjbqnkFE4YturNm3CS).

If you think there is a better way one can learn 3d.js or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on 3d.js that are missing or you wish something was added, you can say it here.

**Comment by abmeena** [comment]
https://classroom.udacity.com/courses/ud507

**Comment by nikitavoloboev** [comment]
Added it. Thank you @abmeena
