### ISSUE TITLE
best path for learning angularJS

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#687]
Take a look [here](https://my.mindnode.com/QYBozsiUWZjbqguqyKSUV3psfhganW7PB1Wapxax).

If you think there is a better way one can learn angularJS or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on angularJS that are missing or you wish something was added, you can say it here.

**Comment by wheelsonthego** [comment]
Angular 2 should probably be a sibling of AngularJS, not a child.  Thanks!

**Comment by nikitavoloboev** [comment]
What do you mean @wheelsonthego 

Would this work? 

![2017-06-13 at 08 47](https://user-images.githubusercontent.com/6391776/27069430-f19ac074-5014-11e7-90c1-0150aded48b0.png)

**Comment by akashpjames** [comment]
I don't think what you have shown in the above picture is correct. One who wants to learn angularjs can't learn anything from the angular 2 framework. 
This is the website of angularJS framework --> https://angularjs.org/
This is the website of angular 2 framework --> https://angular.io/

Maybe, you can show two children when people search for Angular and those can be AngularJS and Angular2.
