### ISSUE TITLE
best path for learning software development

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#690]
Take a look [here](https://my.mindnode.com/C6qyyeVEzfVCyvpxD7digZzzGxV8hvcwdzAkkpjF).

If you think there is a better way one can learn software development or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on software development that are missing or you wish something was added, you can say it here.

**Comment by rogeliotg** [comment]
how do you add a link to another mindmap (web development)?

**Comment by nikitavoloboev** [comment]
I add it currently. In future other people will be able to do it. You want to link to webdev from software development?

**Comment by rogeliotg** [comment]
yes, is what I say. IMHO you must let visitors edit mind maps with ease, and need some automated process to crab the web and add automatically contents and links to the mind maps, in order to be succesfull. If you intent to put every mind map on github and obligue people to be github users, you will only improve development related mind maps.

**Comment by rogeliotg** [comment]
You need:
     -by type: scientific development, games development, data management (business) development, content development (cms, web design), hardware drivers and embedded software (cars, etc), IA development, machine learning, etc.
-by platform: windows, android, ios, web, mac, xbox, playstation, linux, hardware
-by architecture: client-server, client only, server only....

**Comment by nikitavoloboev** [comment]
I agree with you and we will add automation and perhaps some web crawling too. However I want these maps to be human curated and not be curated by some algorithm since algorithms can't properly judge how efficient and good a resource is.

All maps will be live editable though our search engine so no GitHub is required for that, GitHub only comes in to propose the change. We will make this process as simple as possible however and will guide the user in every step of the process. 

In theory it would be as follows : 

1. user presses edit button (contributing guideline opens with what changes will be accepted as far as styling of mind maps goes and content wise)
2. moves nodes around or adds new nodes
3. presses submit 
4. instructions open and he follows them 
5. essentially he arguments why he made the changes he made and submits 
6. trusted person reviews changes and they get merged to the search engine

**Comment by rogeliotg** [comment]
'algorithms can't properly judge how efficient and good a resource is'
google algorithm (that you can integrate) is an example on how to automate people judgement.
algorithms can recolect and fill the gaps, then humans curate results...

**Comment by nikitavoloboev** [comment]
How can we integrate Google's algorithm though? Isn't that property of Google?

**Comment by rogeliotg** [comment]
you can't access google algorithm, just crawl their search results or use their search API.

**Comment by nikitavoloboev** [comment]
But then we would essentially be competing with Google which is a lost game. What's the point of crawling Google if Google already shows the results it crawled in a nice interface.

This takes a wiki like approach of curating links for most efficient learning.
