### ISSUE TITLE
best path for learning devops

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#691]
Take a look [here](https://my.mindnode.com/4pT3AeEEywqSgdxTFBRgq3bmFpLs6s9YSaNMrxZY).

If you think there is a better way one can learn devops or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on devops that are missing or you wish something was added, you can say it here.

**Comment by oogali** [comment]
Perhaps, there could be a branch on data stores? And from that two more branches for NoSQL and RDBMS?

**NoSQL**
- Redis: https://redis.io/
- MongoDB: https://www.mongodb.com/
- https://aws.amazon.com/dynamodb/

**RDBMS**
- MySQL: https://www.mysql.com/
- MariaDB: https://mariadb.org/
- PostgreSQL: https://www.postgresql.org/

**Comment by oogali** [comment]
And additionally package management, as you'll be supporting the distribution of packages that developers create and share with each other?

**Package/Dependency Management**
- Java: Maven (https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html), Gradle (https://docs.gradle.org/current/userguide/artifact_dependencies_tutorial.html)
- NodeJS: npm (https://www.npmjs.com/), Yarn (https://yarnpkg.com)
- PHP: Composer (https://getcomposer.org/)
- Python: pip (https://pip.pypa.io/en/stable/)
- Ruby: rubygems (https://rubygems.org/), Bundler (http://bundler.io/)
