### ISSUE TITLE
best path for learning laravel framework

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#692]
Take a look [here](https://my.mindnode.com/MbpPqGzHzySQesda9G5umY28S3spWRbzgCrGb4Uv).

If you think there is a better way one can learn laravel or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on laravel that are missing or you wish something was added, you can say it here.

**Comment by sayhelloelijah** [comment]
The [Laravel Documentation](http://laravel.com/docs) is really helpful to anyone who would want to learn Laravel and [Laracasts.com](https://laracasts.com) (a video library made primarily for Laravel and other development tools) is also very essential in knowing and understanding the framework.

**Comment by nikitavoloboev** [comment]
Added it. Thank you @sayhelloelijah :)
