### ISSUE TITLE
best path for learning arduino

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#694]
Take a look [here](https://my.mindnode.com/KRHuHfpmq5DzmpfFEgyvSyzQtk9t6oy7faNKbtiL).

If you think there is a better way one can learn arduino or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on arduino that are missing or you wish something was added, you can say it here.

**Comment by chipmc** [comment]
I would link to the Arduino forum: https://forum.arduino.cc/

**Comment by nikitavoloboev** [comment]
Added it. Thank you @chipmc

**Comment by averageunicorn** [comment]
I'm finding these tutorials really helpful:
https://learn.adafruit.com/series/learn-arduino – nicely presented, doesn't need a lot of focus to work through
http://www.ladyada.net/learn/arduino/ – for better understanding of the electronics involved

And this language reference: https://www.arduino.cc/en/Reference/HomePage

**Comment by nikitavoloboev** [comment]
Added it. Thank you @averageunicorn
