### ISSUE TITLE
best path for learning spanish language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#698]
Take a look [here](https://my.mindnode.com/xb6QwzqtZ2sZ2ryvTeXhA8PnUdzFTWZocEoCxeZp).

If you think there is a better way one can learn spanish language or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on spanish language that are missing or you wish something was added, you can say it here.

**Comment by astrikoscode** [comment]
Absolutely love this. Has samples sentences/examples,detailed usage, phrases, conjugations, vocal pronunciation!
http://www.spanishdict.com

**Comment by andersontr15** [comment]
Yeah I have a good suggestion for learning Spanish. Check out clozemaster.com 

https://www.clozemaster.com/about

**Comment by nikitavoloboev** [comment]
Added it. Thank you @andersontr15

**Comment by andersontr15** [comment]
Also, here's a cool article by the founder of the site, putting some perspective into a potential outcome of using the site. https://medium.com/@clozemaster/the-harry-potter-index-c45e8c14f1bf

**Comment by rparthas** [comment]
How about memrise ? http://memrise.com

**Comment by nikitavoloboev** [comment]
Added it. Thank you @rparthas
