### ISSUE TITLE
best path for learning french language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#699]
Take a look [here](https://my.mindnode.com/44Pdg9ZnUsddwk5iWYwH2q2a5xHspBesoDQ2HY31).

If you think there is a better way one can learn french language or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on french language that are missing or you wish something was added, you can say it here.

**Comment by candress** [comment]
https://bonpatron.com/en/ is an excellent resource.  It can correct grammar structure, provide suggestions for your sentences and even has learning modules.

**Comment by nikitavoloboev** [comment]
Added it. Thank you @candress

**Comment by candress** [comment]
It might also be good to add a feature like google's "I'm feeling lucky" or to allow users to indicate what they are interested in and then have subjects suggested to them :)

**Comment by nikitavoloboev** [comment]
We have that in a way. You can just press enter on our suggested results and jump through what things you can learn. :)

**Comment by nikitavoloboev** [comment]
As for more 'personalised learning', yeah we plan to add that soon too. :)

**Comment by Guitaricet** [comment]
I am learning french at babbel.com. They have pretty good lessons. Although you must pay about $40 per half-year to get access to most of them, I think it is a fare price. However, vocabulary exercises are poor, compared to duolingo, but it is possible to combine them both.

Also, Anki is a great (and free) tool for vocabulary.
