### ISSUE TITLE
best path for learning WebAssembly

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#703]
Take a look [here](https://my.mindnode.com/hGPfuwm3pbzHXVVmB3kGRJKcPGPgeZAVFQGztxHW).

If you think there is a better way one can learn WebAssembly or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on WebAssembly that are missing or you wish something was added, you can say it here.

**Comment by drenther** [comment]
https://egghead.io/courses/get-started-using-webassembly-wasm is good introductory video course.

**Comment by nikitavoloboev** [comment]
Added it. Thank you @drenther
