### ISSUE TITLE
best path for learning .NET framework

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#706]
Take a look [here](https://my.mindnode.com/p6P2zXxZjuHy2pwzzy6yi14hPD8Nd4BQj6vraSAi).

If you think there is a better way one can learn .NET or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on .NET that are missing or you wish something was added, you can say it here.

**Comment by Katamori** [comment]
[XNA](https://en.wikipedia.org/wiki/Microsoft_XNA) is a dotnet framework that may worth mentioning here. Of course it's related to game development, too, and also needs some additional resource to learn, so you may want to add a separate map for this one, as well.

**Comment by nikitavoloboev** [comment]
Added it. Thank you @Katamori
