### ISSUE TITLE
best path for learning ruby on rails

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#708]
Take a look [here](https://my.mindnode.com/Cyv3UUXjxZst5FjBnpkSdqn7XtqWmiZsJL3Hqqec).

If you think there is a better way one can learn ruby on rails or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on ruby on rails that are missing or you wish something was added, you can say it here.

**Comment by Khanthulhu** [comment]
Should mention Odin Project. One of the best resources on the internet for learning Rails.

**Comment by nikitavoloboev** [comment]
Thank you @Khanthulhu, I have added it.

**Comment by opensourceame** [comment]
I found Rails for Zombies courses pretty good as a Ruby newbie ..

http://railsforzombies.org

**Comment by UncleJohn418** [comment]
You should mention http://upskillcourses.com/courses/ , they offer a free course that teaches full stack dev with Ruby on Rails as the back end part of the stack.

**Comment by nikitavoloboev** [comment]
Thank you @UncleJohn418 and @opensourceame. I've added them. This course looks great. :)
