### ISSUE TITLE
best path for learning chess

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#712]
Take a look [here](https://my.mindnode.com/PbBNcxWhy1BNfFyCcDGutjyYwBBquHpTsDPDasTq).

If you think there is a better way one can learn chess or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on chess that are missing or you wish something was added, you can say it here.

**Comment by battez** [comment]
Lichess.org is absolutely the best free website for games with others, with included training puzzles , computer analysis, automatic annotations and more.

**Comment by nikitavoloboev** [comment]
Added it. Thank you @battez
