### ISSUE TITLE
best path for learning blender 3d graphics

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#718]
Take a look [here](https://my.mindnode.com/zr3hcyysGypEUsWfPBqat9kSpTpkQzjb6NG7K5EL).

If you think there is a better way one can learn blender or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on blender that are missing or you wish something was added, you can say it here.

**Comment by kannix** [comment]
link to stackexchange is wrong (points to https://bitcoin.stackexchange.com/) please change it to https://blender.stackexchange.com/

**Comment by nikitavoloboev** [comment]
Thank you @kannix, I changed it now. Will be up shortly. :)

**Comment by dpoljak** [comment]
Blender guru website is a great resource for learning Blender and keeping up with the newest additions to the program itself. 
https://www.blenderguru.com/tutorials

https://blenderartists.org/forum/index.php could also be with blender.stackexchange due to the ammount of active users.
