### ISSUE TITLE
best path for learning jvm

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#725]
Take a look [here](https://my.mindnode.com/XyNZszb6ME9zL5EwesBPTCypXWAJjKfu8g3FxtfQ).

If you think there is a better way one can learn android or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on android that are missing or you wish something was added, you can say it here.

**Comment by MichaelObi** [comment]
[JVM ( java virtual machine) architecture - tutorial by Ranjith ramachandran](https://www.youtube.com/watch?v=ZBJ0u9MaKtM) is a great resource

**Comment by nikitavoloboev** [comment]
Added it. Thank you @MichaelObi
