### ISSUE TITLE
best path for learning text editors

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#729]
Take a look [here](https://my.mindnode.com/sy7bTZuzRx2DGTnB4zrxS8xH3bexEiednueetUm4).

If you think there is a better way one can learn text editors or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on text editors that are missing or you wish something was added, you can say it here.

**Comment by burnett-ghartey** [comment]
Atom should be added

**Comment by nikitavoloboev** [comment]
I [have added](https://my.mindnode.com/sjyyVYFviACirWkDBZuW2CbvwyGbaAAy8aYYnoc2). Thank you.
