### ISSUE TITLE
best path for learning probability theory

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#733]
Take a look [here](https://my.mindnode.com/qnagoHf2YScqPiVBsPpgcB8Dxmdm9ku1TN9eQhTd).

If you think there is a better way one can learn probability theory or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on probability theory that are missing or you wish something was added, you can say it here.

**Comment by Katamori** [comment]
Between "basics" and "normal distribution", I'd suggest adding an intermediate node "probability distributions", as there are numerous example beyond normal (e.g. Bernoulli, Poisson, Pareto, binomial, etc.) and means a major field in probability theory.

**Comment by nikitavoloboev** [comment]
Sounds great. I will make it as separate map and add it. :)
