### ISSUE TITLE
best path for learning markov chains

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#734]
Take a look [here](https://my.mindnode.com/1NpiefgrirDdunaD1stiWpyX3bcQbGMKP79hosmN).

If you think there is a better way one can learn markov chains or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on markov chains that are missing or you wish something was added, you can say it here.

**Comment by hill** [comment]
Hi there... the coding train's A to Z videos are some real practical examples with using markov chains. It's pretty cool! 

The youtube playlist is [https://www.youtube.com/watch?list=PLRqwX-V7Uu6ah9Oqs_BFQIbGIn1XynsVT&v=v4kL0OHuxXs](https://www.youtube.com/watch?list=PLRqwX-V7Uu6ah9Oqs_BFQIbGIn1XynsVT&v=v4kL0OHuxXs)

and his project site / resources: http://shiffman.net/a2z/markov/

**Comment by nikitavoloboev** [comment]
Thank you @hill, I have added it. 💙
