### ISSUE TITLE
best path for learning startups

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#750]
Take a look [here](https://my.mindnode.com/3qMybqBsd4E8yeiP48HYyT6s6aSGx17EMaKffkyk).

If you think there is a better way one can learn startups or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on startups that are missing or you wish something was added, you can say it here.

**Comment by Blake575** [comment]
These are two helpful videos by the YouTuber The Rest of Us that explain how startup contracts and funding works:

Funding: 
https://www.youtube.com/watch?v=677ZtSMr4-4
Contracts:
https://www.youtube.com/watch?v=fcjmVj5fM5k&list=PLthEgYm6PEJn1gNdTSRz6t94K1slNR1Lf&index=2

**Comment by OfficialCJunior** [comment]
Hi!
https://medium.com/product-hunt/28-tools-to-help-you-launch-your-startup-on-a-small-budget-7d5383997bbd
https://medium.com/product-hunt/these-tools-will-help-you-launch-your-startup-e9f9b6662afa 
These links has got tips and tools to get a startup working.

**Comment by nikitavoloboev** [comment]
Added them. Thank you guys.
