### ISSUE TITLE
best path for learning earth science

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#762]
Take a look [here](https://my.mindnode.com/9rmJaLMzJ4Wq59fVfrzF5jA7u3ZFVbUvP1fYNyq3).

If you think there is a better way one can learn earth science or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on earth science that are missing or you wish something was added, you can say it here.

**Comment by Katamori** [comment]
Earth Science [has its Stack Exchange site, as well.](https://earthscience.stackexchange.com/)

**Comment by nikitavoloboev** [comment]
Thank you. I've added it. :)
