### ISSUE TITLE
best path for learning space science

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#763]
Take a look [here](https://my.mindnode.com/rq6MV88ZqvbczWGvz7o7EeXDWaXZvBBvhKxjopwW).

If you think there is a better way one can learn space science or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on space science that are missing or you wish something was added, you can say it here.

**Comment by HazeHub** [comment]
Don't know if this is what space science implies but here is a nice ressource in my opinion : https://risacher.org/rocket/
