### ISSUE TITLE
best path for learning html

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#765]
Take a look [here](https://my.mindnode.com/9XKbbxW8Ft3fzP43bPwtqU3PRhDzp3VjKsqLntQJ).

If you think there is a better way one can learn html or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on html that are missing or you wish something was added, you can say it here.

**Comment by philipwisner** [comment]
The link to articles from has a spelling mistake. It says 17. listing HTML using CSS instead of "linting." Other than that it looks great!

**Comment by nikitavoloboev** [comment]
Thank you @philipwisner. I've changed it.

17:  prefix stands for the year in which the article was written in. I abbreviate it thus 17: means it was written in 2017. We will make it more clear in documentation in our next update. :)

**Comment by jamesjpk123** [comment]
For HTML, freeCodeCamp is a great resource. It has tons of free HTML courses online, that I started a couple months ago. It is not included on the map, even though it is a really awesome "boot camp". Can this be added?

**Comment by nikitavoloboev** [comment]
Yeah of course @jamesjpk123. I actually have Freecodecamp added as basics to web development. But I can link to some modules for HTML from Freecodecamp too. :)
