### ISSUE TITLE
best path for learning css

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#766]
Take a look [here](best path for learning ).

If you think there is a better way one can learn css or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on css that are missing or you wish something was added, you can say it here.

**Comment by bryanph** [comment]
Some resources worth adding :
* CSS3 animations
* flexbox (I usually look at this article https://css-tricks.com/snippets/css/a-guide-to-flexbox/)
* box shadows
* grid

Just overall more detailed stuff

**Comment by nikitavoloboev** [comment]
Added it. Thank you @bryanph :)

**Comment by nglgzz** [comment]
Other two cool resources for CSS: http://flexboxfroggy.com/ and http://cssgridgarden.com/
