### ISSUE TITLE
best path for learning ketogenic diet

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#767]
Take a look [here](https://my.mindnode.com/AoAE4txQminSymyAA5UB4zEPunffJgD5feWVBJeH).

If you think there is a better way one can learn ketogenic diet or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on ketogenic diet that are missing or you wish something was added, you can say it here.

**Comment by wangeleile** [comment]
Well, my first starting point for keto is https://www.reddit.com/r/keto/

**Comment by nikitavoloboev** [comment]
I actually have it included already. Check the reddit logo symbol. :)

**Comment by wangeleile** [comment]
Sorry, I was blind. Maybe you add an title, something like "Keto Forum on Reddit"
