### ISSUE TITLE
best path for learning general relativity

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#768]
Take a look [here](https://my.mindnode.com/Jx67uwFCxmdrGPDEYEvNTzW1GybQ63qapyojnzby).

If you think there is a better way one can learn general relativity or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on general relativity that are missing or you wish something was added, you can say it here.

**Comment by Yurlungur** [comment]
A basic introduction to GR requires at least a background in linear algebra, vector calculus, Newtonian physics (like energy, momentum, etc), and special relativity. (Which requires all the previous topics.) Foreknowledge in differential geometry and electromagnetism (as a field theory) would also help.
