### ISSUE TITLE
best path for learning the universe

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#772]
Take a look [here](https://my.mindnode.com/bvabTANvmfGEqv6e7GwxVtqa5SPy5anapYcyceYi).

If you think there is a better way one can learn the universe or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on universe that are missing or you wish something was added, you can say it here.

**Comment by OfficialCJunior** [comment]
Hi!

I'd like to convey my ideas in making the map of universe more interesting. As the subject is very vast, I think it'd be great if we can start with add something about on theories of how it began, obviously about the Big Bang and put links for the best places to learn about cosmology.

Thanks a lot!

**Comment by nikitavoloboev** [comment]
Hey @OfficialCJunior :)

Yes certainly, the topic is incredibly vast. It is a great idea to include Big Bang and I will add that. Also universe is in [Astrology](https://learn-anything.xyz/space-science/astronomy) so maybe we can expand that too.

**Comment by OfficialCJunior** [comment]
That'd be great. I hadn't checked Astronomy yet, until now. Astronomy is pretty decent. You don't mind me suggesting more on other stuffs too, right?

**Comment by nikitavoloboev** [comment]
Yes of course. Please do. :)
