### ISSUE TITLE
best path for learning world history

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#773]
Take a look [here](https://my.mindnode.com/sht4GTMSXhqqMcJaCU3RD8Z6uSCZRa6Jn66BuWdD).

If you think there is a better way one can learn world history or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on world history that are missing or you wish something was added, you can say it here.

**Comment by Katamori** [comment]
Maybe it's just me, but IMHO it's such a vastly enormous area that it MUST be separated by ages. All the current branches may go to a separate "misc" or "general" branch, but ages themselves must be represented.

E.g. there were way too many wars to list in one huge branch.

**Comment by nikitavoloboev** [comment]
I agree @Katamori 

How would you separate it by age though?

**Comment by Katamori** [comment]
That's a good question, there are many different ways of dividing history to ages.
