### ISSUE TITLE
best path for learning psychedelic drugs

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#789]
Take a look [here](https://my.mindnode.com/x9dBkz2cjvrWKzF8zyALjeJ3uqgDqw2ds8KorBZM).

If you think there is a better way one can learn psychedelic drugs or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on psychedelic drugs that are missing or you wish something was added, you can say it here.

**Comment by mstoaks** [comment]
Typo... "Micodosing" should be "Microdosing"

**Comment by nikitavoloboev** [comment]
Thank you @mstoaks I changed it 💙
