### ISSUE TITLE
best path for learning racket programming language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#792]
Take a look [here](https://my.mindnode.com/1mak5mvoUr33bPPcyQ576x2Nqn7mgZ7gjMxxkopx).

If you think there is a better way one can learn racket or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on racket that are missing or you wish something was added, you can say it here.

**Comment by vityou** [comment]
[The Racket Guide](https://docs.racket-lang.org/guide) is basically a textbook that describes raxket.

**Comment by nikitavoloboev** [comment]
Added it. Thank you @vityou :)
