### ISSUE TITLE
best path for learning d programming language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#798]
Take a look [here](https://my.mindnode.com/FQDyRm9s9ynq8oToMFtAystowVSCmzmaspbXdi4z).

If you think there is a better way one can learn d programming language or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on d programming language that are missing or you wish something was added, you can say it here.

**Comment by whiteisthenewblack** [comment]
[The D programming language](http://amzn.to/1ZTDmqH) deserves a mention I think
