### ISSUE TITLE
best path for learning typefaces

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#805]
Take a look [here](https://my.mindnode.com/ftrsbpaLcU4HiSq91BTXuBnsUFmrh7iqavp6UsVe).

If you think there is a better way one can learn typefaces or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on typefaces that are missing or you wish something was added, you can say it here.

**Comment by mrlund** [comment]
Suggested addition: https://www.coursera.org/
