### ISSUE TITLE
best path for learning microsoft azure

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#816]
Take a look [here](https://my.mindnode.com/bskpRmBhBQvN6KDV83xxMPyZspkMpwtpvUykMxpZ).

If you think there is a better way one can learn microsoft azure or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on microsoft azure that are missing or you wish something was added, you can say it here.

**Comment by aligneddev** [comment]
This can be a really helpful link for this map: https://azure.microsoft.com/en-in/documentation/learning-paths/

**Comment by nikitavoloboev** [comment]
Thank you @aligneddev, I have added it 💙
