### ISSUE TITLE
best path for learning card games

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#834]
Take a look [here](https://my.mindnode.com/JZzDhgP2sktZ3pD2NgouS6ppfRsPKKm15Un1ZtMV).

If you think there is a better way one can learn card games or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on card games that are missing or you wish something was added, you can say it here.

**Comment by mrlund** [comment]
Suggested addition: https://www.coursera.org/
