### ISSUE TITLE
best path for learning RxJS

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#858]
Take a look [here](https://my.mindnode.com/rdUzwvGv7Gpa2z1ZhPrzDsmpR6D1nCL6VN6zFssB).

If you think there is a better way one can learn RxJS or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on RxJS that are missing or you wish something was added, you can say it here.

**Comment by acailly** [comment]
Here's one missing amazing resource : https://rxviz.com/

**Comment by nikitavoloboev** [comment]
Added it. Thank you @acailly

**Comment by alexonaci** [comment]
Hello,

Here is a great resource on learning RxJs by exercise:

http://reactivex.io/learnrx/

And some good and useful articles on Observables:

https://medium.com/@benlesh/learning-observable-by-building-observable-d5da57405d87

https://medium.com/@benlesh/hot-vs-cold-observables-f8094ed53339

**Comment by nikitavoloboev** [comment]
Added it. Thank you @alexonaci
