### ISSUE TITLE
best path for learning minimalism

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#863]
Take a look [here](https://my.mindnode.com/vZ3FssCtMk5Q8HjqW8Wtcr178dJ1iz2HyHQEc2kj).

If you think there is a better way one can learn minimalism or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on minimalism that are missing or you wish something was added, you can say it here.

**Comment by mattburman** [comment]
Light by COCO has no videos, and seems to have quit youtube https://www.youtube.com/channel/UCp12IFoANz_tEY6YgZFqohA/videos

**Comment by nikitavoloboev** [comment]
Wow, that's really sad to hear. Really loved her videos. :(

**Comment by mattburman** [comment]
are they archived anywhere?

**Comment by nikitavoloboev** [comment]
Tried looking now and can't find any. That's really strange though. I do hope she comes back, she had some really awesome videos.

**Comment by nikitavoloboev** [comment]
On the funny side, she does have the lightest youtube `subscribers > # of videos` channel ever. :D

**Comment by mattburman** [comment]
Maybe they are practising minimalism?

**Comment by nikitavoloboev** [comment]
It's just one person. But yeah. I understand her stance on wanting to commit to only one platform and she chose Instagram.

**Comment by mattburman** [comment]
I try to just default to gender-neutral pronouns. It's minimalist too ;)
I guess I'll follow her on instagram. It's probably not a high quality resource for LA though.

**Comment by mattburman** [comment]
"The Minimalists" have some good content. Blogs, podcasts, books, and a film http://www.theminimalists.com/start/

**Comment by nikitavoloboev** [comment]
Sweet. Will add them. Yeah her videos were actually quite educational, Instagram is more for self expression.

If you want, you can write an article on minimalism and we can add it. :)

I am actually writing one now too soon but its more about practical minimalism and my approach on GTD.

**Comment by mattburman** [comment]
I've been thinking about writing and/or making videos on how I've been applying minimalism recently.

One common thing people do is an "x item challenge" - by listing all the things they own to get it under some x. This is my "list": https://my.mindnode.com/bMJipUbnziz1fvY5fEq4TtVn8pcAneUPrgXq2gn7 - I'm not there yet. Sorta starting from scratch and ignoring most things I currently own to rebuy - especially clothes (less, but higher quality).

Another set of videos I've been thinking about is specifically about travel minimalism and bag packing. I've been trying to "fit my life into a backpack" - making it convenient to just pick up my bag and leave prepared at all times.

**Comment by nikitavoloboev** [comment]
That's an awesome idea. I actually have a map like this too although I didn't commit yet to filling it. I even had an idea of making an app specifically to track a person's belongings but then I also had an idea to make an app for quotes. But then MindNode came along. :)

It's really awesome though that nowadays you really do need so few things. I think a video or tutorial about how to keep your digital life minimal enough is super valuable and I have not seen anyone address this well yet. 

It's something I try very hard to do, to be aware of both my digital fingerprint on the web and where my content is placed and where each piece of content (or data) should go. Streamlining these things to a certain routine is really helpful in t

**Comment by nikitavoloboev** [comment]
I maintain a personal flow map that looks kind of like this : 

![2017-07-07 at 23 06](https://user-images.githubusercontent.com/6391776/27976969-faf5c1f2-6368-11e7-90ea-7944640bd997.png)

And in there I try to outline mental processes and routines I would like to follow.

**Comment by mattburman** [comment]
That's awesome. Whilst I've been "resetting my life", I've been focusing on physical minimalism - all the physical "stuff" I have taking up my mental space.

But streamlining the digital "stuff" that is affecting me is also something I want to do. Super interested in that, and not seen that many resources about that - a lot of it does seem to be about physical stuff.

I want to do this all to a really nice point before I graduate, so I have maximum freedom to do what I want in this world with least friction. But minimalism is a way of life and has to be continually practised :-)
