### ISSUE TITLE
best path for learning aerospace engineering

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#879]
Take a look [here](https://my.mindnode.com/TTXSvmsSaVq3JpJy8ytYbbR9w5vxoUsNmds5UxuW).

If you think there is a better way one can learn aerospace engineering or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on aerospace engineering that are missing or you wish something was added, you can say it here.

**Comment by Psykodeliks** [comment]
Found this on Reddit, there are no results when I searched for Visual Basic.

**Comment by nikitavoloboev** [comment]
Yeah sorry about that. I have added it now, will be up shortly. :)

**Comment by Psykodeliks** [comment]
Thank you! I landed a freelance job... Just gotta learn the basics first so
I really appreciate it.
