### ISSUE TITLE
best path for learning product management

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#883]
Take a look [here](https://my.mindnode.com/sCFMbq9sV42TeFcyXvipGFavex3Q4MbAkRgSsgkz).

If you think there is a better way one can learn product management or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on product management that are missing or you wish something was added, you can say it here.

**Comment by shubham-evive** [comment]
These are good to be added:
  - https://yilunzh.com/pm/
  - http://ask.goodproductmanager.com/

**Comment by nikitavoloboev** [comment]
Thank you @shubham-evive, I have added it. 💙
