### ISSUE TITLE
best path for learning accounting

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#892]
Take a look [here](https://my.mindnode.com/xbjRCSkQDphpvvvZ8FZcgCazpajSKUkEV8uTz7pE).

If you think there is a better way one can learn accounting or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on accounting that are missing or you wish something was added, you can say it here.

**Comment by xzhao30** [comment]
There is some other important brancher like managerial accounting, tax accounting and auditing.
