### ISSUE TITLE
best path for learning relationships

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#896]
Take a look [here](https://my.mindnode.com/FdxqYCv77bAF9ebSfAtb6Afz5BEu4qsWLzJJ4UEk).

If you think there is a better way one can learn relationships or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on relationships that are missing or you wish something was added, you can say it here.

**Comment by averageunicorn** [comment]
Advice about tons of different relationship/friendship/family/etc issues: https://captainawkward.com/

And this seems relevant for openly negotiating relationships: http://qpadvice.tumblr.com/post/98302305387/hello-recently-i-was-surprised-by-the-amount-of

And, not sure if sex and kink should be part of "relationships" or separate, but:
https://www.autostraddle.com/you-need-help-here-is-a-worksheet-to-help-you-talk-to-partners-about-sex-237385/
https://pervocracy.blogspot.co.at/2012/02/concise-kink-worksheet.html
https://pervocracy.blogspot.co.at/p/worksheets.html
