### ISSUE TITLE
best path for learning python libraries

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#897]
Take a look [here](https://my.mindnode.com/kDFfqVBWhK4htp3sQLpLmxgGLxhTCk8Qx4mqGRaR).

If you think there is a better way one can learn python libraries or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on python libraries that are missing or you wish something was added, you can say it here.

**Comment by secsilm** [comment]
[Pandas](http://pandas.pydata.org/) is the most popular library in data science. I think it should be include.

**Comment by Diptanshu8** [comment]
Also, a new branch pointing to **Web scrapping** could be added and then accordingly,**BeautifulSoup**, **Requests** and **Selenium** could be added.
