### ISSUE TITLE
best path for learning encryption

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#908]
Take a look [here](https://my.mindnode.com/qWEzhMurSUCvDyqXq2p6nnUd5cdKSrq6vUnpbNrp).

If you think there is a better way one can learn encryption or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on encryption that are missing or you wish something was added, you can say it here.

**Comment by somnathrakshit** [comment]
[https://www.khanacademy.org/computing/computer-science/cryptography](Journey into cryptography | Khan Academy) should be added. It's amazing.

**Comment by nikitavoloboev** [comment]
It is amazing. I have added it. 💙

**Comment by OfficialCJunior** [comment]
Shouldn't we add something on how to encrypt e-mails i.e about PGP and all?

**Comment by nikitavoloboev** [comment]
Yeah we can. PGP is great.
