### ISSUE TITLE
best path for learning effective learning

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#915]
Take a look [here](https://my.mindnode.com/7yPviE4oYJJ5xRmDYrTQfqWCkydzPoRXQAQ3nyAJ).

If you think there is a better way one can learn effective learning or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on effective learning that are missing or you wish something was added, you can say it here.

**Comment by Blake575** [comment]
This is a wiki that uses simplified language:
https://simple.wikipedia.org/wiki/Main_Page
I use this with difficult subjects because it breaks it down to an easier to understand explanation.
