### ISSUE TITLE
best path for learning sorting algorithms

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#932]
Take a look [here](https://my.mindnode.com/wfdPrx9rsUeUpwwspRgsM741LKciWLMeUev8ML1u).

If you think there is a better way one can learn sorting algorithms or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on sorting algorithms that are missing or you wish something was added, you can say it here.

**Comment by goxul** [comment]
https://visualgo.net/en/sorting?slide=1

This is a neat resource for sorting algorithms (or algorithms in general)

**Comment by nikitavoloboev** [comment]
Thank you @goxul. I have added it. Will be up shortly. 💙
