### ISSUE TITLE
best path for learning big O notation

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#933]
Take a look [here](https://my.mindnode.com/wptdyX9aF7U63EaydGsif5s49ypXyCJ5qq2Gyduh).

If you think there is a better way one can learn big O notation or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on big O notation that are missing or you wish something was added, you can say it here.

**Comment by wendydra** [comment]
In my experience, issues with learning big O generally stem from a loss / lack of familiarity with logarithms.

Maybe add the Khan academy course on logarithms (such as why is log n better than n squared?) or maybe a more targeted class.

**Comment by nikitavoloboev** [comment]
I agree with you. We [plan to add this feature](https://github.com/learn-anything/search-engine/issues/30) where we specify prerequisite knowledge for each of the maps and we can solve this with that.

But for now I will add a logarithm course. Thank you.

**Comment by wendydra** [comment]
Oh I had not seen that part, this looks fantastic. 

Glad it was useful :)
