### ISSUE TITLE
best path for learning anatomy

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#934]
Take a look [here](https://my.mindnode.com/9uv1CLtwKkZZA4AV4q5zmyenvRpFQsryP6Z1iW2e).

If you think there is a better way one can learn anatomy or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on anatomy that are missing or you wish something was added, you can say it here.

**Comment by astrikoscode** [comment]
http://anatomyzone.com
http://biodigital.com (free & paid options)
http://www.med.umich.edu/lrc/coursepages/m1/anatomy2010/html/INDEX.html

Here are my favorites!
