### ISSUE TITLE
best path for learning logic programming

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#936]
Take a look [here](https://my.mindnode.com/DRHzPabqxynXg22yn4qyossXjbdx8y8sVZkWNmjx).

If you think there is a better way one can learn logic programming or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on logic programming that are missing or you wish something was added, you can say it here.

**Comment by triska** [comment]
The node "logic programming" should link to "prolog" which is the oldest and most popular logic&nbsp;programming language.

**Comment by nikitavoloboev** [comment]
I have added it Thank you @triska.
