### ISSUE TITLE
best path for practicing programming 

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#947]
Take a look [here](https://my.mindnode.com/bF5YW76MmjiqqesqcYAd8SWU1TzgqxbczE7q58y1).

If you think there is a better way one can learn to practice programming or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on practicing programming that are missing or you wish something was added, you can say it here.

**Comment by shotgunner** [comment]
[my code school](http://mycodeschool.com)
