### ISSUE TITLE
best path for learning quantum information

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#952]
Take a look [here](https://my.mindnode.com/6nxrnv5quSLhpb7nwdAJ2BiaKFDxE6oQeeoHcW69).

If you think there is a better way one can learn quantum information or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on quantum information that are missing or you wish something was added, you can say it here.

**Comment by nicqrocks** [comment]
Seems like it should have a reference to [Quantum Superposition](http://www.wikiwand.com/en/Quantum_superposition) since it is closely linked.

**Comment by nikitavoloboev** [comment]
Thank you @nicqrocks, I have added it.
