### ISSUE TITLE
best path for learning meditation

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#954]
Take a look [here](https://my.mindnode.com/EWHvLZs2foxPwdafxLiQBZLRAxepeCEybvzpzGpv).

If you think there is a better way one can learn meditation or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on meditation that are missing or you wish something was added, you can say it here.

**Comment by OfficialCJunior** [comment]
I hope this will help.
http://how-to-meditate.org/
http://meditation.org.au/class1.asp?mobilecheck=true

**Comment by OfficialCJunior** [comment]
I hope this is worth adding.
http://how-to-meditate.org/
http://meditation.org.au/class1.asp?mobilecheck=true

**Comment by nikitavoloboev** [comment]
Added it. Thank you @OfficialCJunior

**Comment by nikitavoloboev** [comment]
Added it. Thank you @Blake575

**Comment by mattburman** [comment]
Worth adding apps such as Calm and Headspace.
