### ISSUE TITLE
best path for learning cybersecurity

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#955]
Take a look [here](https://my.mindnode.com/HstinnJz9VyxRxHsr3sAQzCWPuFXqLYBMzkX5AoM).

If you think there is a better way one can learn cybersecurity or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on cybersecurity that are missing or you wish something was added, you can say it here.

**Comment by Blake575** [comment]
Future Crimes by Marc Goodman.
