### ISSUE TITLE
best path for learning yoga

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#962]
Take a look [here](https://my.mindnode.com/BypM4A44UVcpNJL6pfPAsQDznQJQX9MVBDa52AyG).

If you think there is a better way one can learn yoga or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on yoga that are missing or you wish something was added, you can say it here.

**Comment by OfficialCJunior** [comment]
These sites offer some good stuff too?
https://www.doyogawithme.com/
http://www.learningyoga.com/
http://www.yogabasics.com/

**Comment by nikitavoloboev** [comment]
Added it. Thank you @OfficialCJunior
