### ISSUE TITLE
Better heuristic for path

### ISSUE THREAD

**Issue by triska** [learn-anything/maps#966]
For example: Currently, when you search for "Prolog", you get taken to the [**prolog**](https://learn-anything.xyz/programming/programming-languages/prolog)&nbsp;node, showing the following&nbsp;path:

[programming](https://learn-anything.xyz/programming) &rightarrow; [programming&nbsp;languages](https://learn-anything.xyz/programming/programming-languages) &rightarrow; [prolog](https://learn-anything.xyz/programming/programming-languages/prolog)

That's certainly a valid derivation.

However, I think displaying the following path instead would be even more useful:

[programming](https://learn-anything.xyz/programming) &rightarrow; [**programming&nbsp;paradigms**](https://learn-anything.xyz/programming/programming-paradigms) &rightarrow; [**logic&nbsp;programming**](https://learn-anything.xyz/programming/programming-paradigms/logic-programming) &rightarrow; [prolog](https://learn-anything.xyz/programming/programming-languages/prolog)

This of course generalizes to other topics. Maybe there is general heuristic for selecting those paths that convey, in a sense, the "most useful" derivation.

**Comment by nikitavoloboev** [comment]
A better heuristic is certainly something would be improved too. The problem with that is that I other languages will need to follow a similar format. i.e 

programming => prog paradigms => multi-paradigm => c

But multi-paradigm is not a map and I can't make it a map or rather I don't want to as its not a big topic. I currently just bundle all languages under programming languages and visualise connections there but these connections get lost in the path naming.

We will try to think of a better solution for this. :)

**Comment by triska** [comment]
I think it would be best to devise a **general** solution, not only for programming languages, but for all topics!

The question is always the same: If there are several possible paths to any topic, pick one that (for example!) spreads the involved categories "most broadly", in some yet to be defined sense, or by some other criterion that should apply to *any* topic equally.

**Comment by nikitavoloboev** [comment]
Yes certainly. A general solution is good. 

I actually added prolog before I added logic programming as a mind map. :)

**Comment by nikitavoloboev** [comment]
Speaking of logic programming is there anything interesting that you think I can add to either prolog or logic programming? :)

Perhaps there is another language that is also interesting and in the same domain.

**Comment by triska** [comment]
For example, it would be completely OK if, as a result, "prolog" would be resolved as:

programming &rightarrow; programming paradigms &rightarrow; logic programming &rightarrow; prolog

yet, at the same time "c" would be resolved as:

programming &rightarrow; programming languages &rightarrow; c

*or*

programming &rightarrow; programming paradigms &rightarrow; imperative &rightarrow; c

or by some other path, if that is "best" according to the yet to be defined heuristic.

**Comment by triska** [comment]
A further prominent logic programming language is [**Mercury**](https://en.wikipedia.org/wiki/Mercury_(programming_language)), available from:

http://www.mercurylang.org/
