### ISSUE TITLE
best path for learning arabic language

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#970]
Take a look [here](https://my.mindnode.com/Mx2GVkpwTr6YasH6NsRqcxN9uvXG6aHyob1A61vz).

If you think there is a better way one can learn arabic language or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on arabic language that are missing or you wish something was added, you can say it here.

**Comment by turnono** [comment]
Hi, can you add my resource. It helps users to learn how to grammatically analyse Arabic texts step by step, can be found at www.learningmuslim.com.
