### ISSUE TITLE
best path for learning ES6

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#973]
Take a look [here](https://my.mindnode.com/rNhr9Nq5D6yWCM6rjQLYyLyoxtomM6yK62VZS4Ud).

If you think there is a better way one can learn ES6 or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on ES6 that are missing or you wish something was added, you can say it here.

**Comment by ParaBolt** [comment]
http://exploringjs.com/es6/

**Comment by nikitavoloboev** [comment]
Added it. Thank you @ParaBolt
