### ISSUE TITLE
best path for learning human rights

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#981]
Take a look [here](https://my.mindnode.com/aU9xyy3HCSQpoDaL8yzyfyb7ep2SiGqcw7RinZWh).

If you think there is a better way one can learn human rights or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on human rights that are missing or you wish something was added, you can say it here.

**Comment by OfficialCJunior** [comment]
Hi! 

I feel these links are valuable and worth added too.
https://www.wikiwand.com/en/Human_rights has covered most of it.
https://www.un.org/en/universal-declaration-human-rights contains the list of all UN Human Rights.

And if it's good to add about human rights group, who fights for them, there is
https://www.wikiwand.com/en/Human_rights_group 
https://www.wikiwand.com/en/Human_rights_activists
https://www.amnesty.org/en/
https://www.hrw.org/
Thank you! :)

**Comment by nikitavoloboev** [comment]
Will add now. Thank you @OfficialCJunior 💙
