### ISSUE TITLE
best path for learning cold war

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#985]
Take a look [here](https://my.mindnode.com/Udm6Ch9EyzcmjCxztVGzRshsDbMgHNEhLMKyBGqc).

If you think there is a better way one can learn cold war or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on cold war that are missing or you wish something was added, you can say it here.

**Comment by OfficialCJunior** [comment]
Hi.
https://www.wikiwand.com/en/Cold_War - has a great article.
https://www.khanacademy.org/humanities/ap-us-history/period-8/apush-postwar-era/v/origins-of-the-cold-war - Offers a series of videos and articles
Thank you! :)

**Comment by nikitavoloboev** [comment]
The top level node is nearly always a wiki so wiki articles are always included already but I will add KA now :)
