### ISSUE TITLE
best path for learning facial recognition 

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#986]
Take a look [here](https://my.mindnode.com/niJKPUBTXEr67jrMUCGAyhmsWqmhygA2uR1LN3i4).

If you think there is a better way one can learn facial recognition or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on facial recognition that are missing or you wish something was added, you can say it here.

**Comment by mrlund** [comment]
Suggested addition: http://learnanythingdemo.azurewebsites.net/Home/About
