### ISSUE TITLE
best path for learning trigonometry

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#991]
Take a look [here](https://my.mindnode.com/Rnex24pLbmpMpYzuCG1y4uRyjp88Hv7ExoLLyJJK).

If you think there is a better way one can learn trigonometry or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on trigonometry that are missing or you wish something was added, you can say it here.

**Comment by OfficialCJunior** [comment]
Hi!
https://www.mathsisfun.com/algebra/trigonometry.html
seems to have information that is worth adding

**Comment by nikitavoloboev** [comment]
I much prefer [this](https://betterexplained.com/articles/intuitive-trigonometry/), I think it is better

**Comment by OfficialCJunior** [comment]
Yeah. It has got them all, and the videos are good too. You may add that.
