### ISSUE TITLE
best path for learning music production

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#992]
Take a look [here](https://my.mindnode.com/ANRJHMcssy9Xq6HAHqbBysQm9nZg8urAYb7LVZSD).

If you think there is a better way one can learn music production or you think the way the nodes are structured is wrong, please say it here.

Also if you think there are some really amazing resources on music production that are missing or you wish something was added, you can say it here.

**Comment by LarsonRogers** [comment]
Sorry for being MIA for so long, but [here's](https://learningmusic.ableton.com/index.html) an incredible resource from Ableton for learning the basics of music production. Quite literally the most interactive and engaging tutorial format that I've encountered.

**Comment by nikitavoloboev** [comment]
Added it. Thank you @LarsonRogers
