### ISSUE TITLE
add more interesting humans

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/maps#998]
Take a look [here](https://github.com/learn-anything/humans).

If you think there there is some awesome person that is missing from the list that you wish was added, please say it here.

**Comment by heidzelaine** [comment]
I have a few names to add! 

Under writing:
John Milton 
Harriet E Wilson

Under music:
Irving Berlin
Imogen Heap

**Comment by nikitavoloboev** [comment]
Will add them now, thank you 💙
